### ISSUE TITLE
V4-dev.18 version crash at sockaddr_cmpf()

### ISSUE THREAD

**Issue by tianyangfengbyte** [nfs-ganesha/nfs-ganesha#1046]
Hi
We  found that ganesha would crash occasionally in sockaddr_cmpf(), the ganesha version we used is V4-dev.18(commit is https://github.com/nfs-ganesha/nfs-ganesha/commit/64f0146c0c30a5fa9b7f34324d9238d7fbfc2624). 
And the stack is following:
#0  sockaddr_cmpf (addr1=0x7f4fbcd8b838, addr2=0x6f6c62202c3638b0, ignore_port=false) at bytenas-ganesha/src/RPCAL/rpc_tools.c:297
#1  0x00007f50944e0a9b in opr_rbtree_lookup () from /opt/tiger/ganesha_deploy/lib/libntirpc.so.3.2
#2  0x00000000006e2b0c in nfs_dupreq_get_drc (req=0x7f4edd5fa000) at bytenas-ganesha/src/RPCAL/nfs_dupreq.c:636
#3  nfs_dupreq_start(nfs_request*, svc_req*) () at bytenas-ganesha/src/RPCAL/nfs_dupreq.c:1040
#4  0x00000000007a35b2 in nfs_rpc_process_request(nfs_request*) () at bytenas-ganesha/src/MainNFSD/nfs_worker_thread.c:1005
#5  0x00007f50944f352c in svc_request () from /opt/tiger/ganesha_deploy/lib/libntirpc.so.3.2
#6  0x00007f50944f0841 in svc_rqst_xprt_task_recv () from /opt/tiger/ganesha_deploy/lib/libntirpc.so.3.2
#7  0x00007f50944f133b in svc_rqst_epoll_loop () from /opt/tiger/ganesha_deploy/lib/libntirpc.so.3.2
#8  0x00007f50944fc54a in work_pool_thread () from /opt/tiger/ganesha_deploy/lib/libntirpc.so.3.2
#9  0x00007f5091e87ca9 in start_thread (arg=0x7f4fbcdff700) at pthread_create.c:486
#10 0x00007f508d19276f in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95

the code in #0 is:
![d5d46c8c-23df-4543-996d-e93fc9a3394c](https://github.com/nfs-ganesha/nfs-ganesha/assets/130728973/42d7dff0-4c18-4cb6-b1a4-43fc7a1276c9)

We debug in gdb and found addr2 cant be access in stack:
![image](https://github.com/nfs-ganesha/nfs-ganesha/assets/130728973/28e8b9ad-107a-48c2-9aa1-817695abd42d)

I wonder if anyone has seen this stack before?
Thanks

**Comment by ffilz** [comment]
I haven't seen that stack before. There have been a few DRC changes since then, though they don't look likely to affect this situation.

Why are you using V4-dev.18 and not at least V4.0?

Note also that since then, we have released V5.0 and several updates, so we really aren't supporting V4.x anymore.

Please at least try on the latest V5.7

**Comment by tianyangfengbyte** [comment]
ok， i will use the latest version. Thanks

**Comment by ffilz** [comment]
I will keep this open until you have a chance to verify you don't hit the issue on V5.7

**Comment by pranavprakash20** [comment]
@ffilz 
We have been running regressions and other checks over the last few builds and haven't hit this crash so far. 
Can we mark it as closed ?
Do you suggest any specific checks to be done to validate this issue is not seen in recent builds?

**Comment by ffilz** [comment]
Yea, this is over a year old with no response from the originator.

Closing.
