### ISSUE TITLE
Ganesha crash while running cthon in loop

### ISSUE THREAD

**Issue by yogendra-t** [nfs-ganesha/nfs-ganesha#1068]
Below crash  seen while running cthon in a loop with ganesha 5.7

(gdb) bt
#0  0x00007f7136949b8f in raise () from /lib64/libpthread.so.0
#1  0x00007f713863ce71 in crash_handler (signo=11, info=0x7f71104c32f0, ctx=0x7f71104c31c0)
    at /usr/src/debug/gpfs.nfs-ganesha-5.7-ibm007.00.el8.x86_64/MainNFSD/nfs_init.c:256
#2  <signal handler called>
#3  0x00007f7138395bec in remove_recolour (head=0x7f70f4005d08, parent=0x3c6cf70, node=0x0)
    at /usr/src/debug/gpfs.nfs-ganesha-5.7-ibm007.00.el8.x86_64/libntirpc/src/rbtree.c:331
#4  0x00007f7138396021 in opr_rbtree_remove (head=0x7f70f4005d08, node=0x7f70f40981d0)
    at /usr/src/debug/gpfs.nfs-ganesha-5.7-ibm007.00.el8.x86_64/libntirpc/src/rbtree.c:453
#5  0x00007f713866d578 in rbtree_x_cached_remove (xt=0x7f70f40066c8, t=0x7f70f4005c50, nk=0x3c70080, hk=5285859450032694740)
    at /usr/src/debug/gpfs.nfs-ganesha-5.7-ibm007.00.el8.x86_64/libntirpc/ntirpc/misc/rbtree_x.h:151
#6  0x00007f7138672a0d in nfs_dupreq_finish (reqnfs=0x7f70f4077c40, rc=NFS_REQ_OK) at /usr/src/debug/gpfs.nfs-ganesha-5.7-ibm007.00.el8.x86_64/RPCAL/nfs_dupreq.c:1306
#7  0x00007f71386356ca in complete_request (reqdata=0x7f70f4077c40, rc=NFS_REQ_OK)
    at /usr/src/debug/gpfs.nfs-ganesha-5.7-ibm007.00.el8.x86_64/MainNFSD/nfs_worker_thread.c:809
#8  0x00007f7138637c07 in nfs_rpc_process_request (reqdata=0x7f70f4077c40, retry=false)
    at /usr/src/debug/gpfs.nfs-ganesha-5.7-ibm007.00.el8.x86_64/MainNFSD/nfs_worker_thread.c:1538
#9  0x00007f713863815f in nfs_rpc_valid_NFS (req=0x7f70f4077c40) at /usr/src/debug/gpfs.nfs-ganesha-5.7-ibm007.00.el8.x86_64/MainNFSD/nfs_worker_thread.c:1732
#10 0x00007f71383ae723 in svc_vc_decode (req=0x7f70f4077c40) at /usr/src/debug/gpfs.nfs-ganesha-5.7-ibm007.00.el8.x86_64/libntirpc/src/svc_vc.c:1046
#11 0x00007f71383a9c41 in svc_request (xprt=0x7f70f8000b60, xdrs=0x7f70f40802a0) at /usr/src/debug/gpfs.nfs-ganesha-5.7-ibm007.00.el8.x86_64/libntirpc/src/svc_rqst.c:1202
#12 0x00007f71383ae628 in svc_vc_recv (xprt=0x7f70f8000b60) at /usr/src/debug/gpfs.nfs-ganesha-5.7-ibm007.00.el8.x86_64/libntirpc/src/svc_vc.c:1019
#13 0x00007f71383a9bc1 in svc_rqst_xprt_task_recv (wpe=0x7f70f8000e28) at /usr/src/debug/gpfs.nfs-ganesha-5.7-ibm007.00.el8.x86_64/libntirpc/src/svc_rqst.c:1183
#14 0x00007f71383aa755 in svc_rqst_epoll_loop (wpe=0x3c0ab98) at /usr/src/debug/gpfs.nfs-ganesha-5.7-ibm007.00.el8.x86_64/libntirpc/src/svc_rqst.c:1564
#15 0x00007f71383b5c1c in work_pool_thread (arg=0x7f70ec0afec0) at /usr/src/debug/gpfs.nfs-ganesha-5.7-ibm007.00.el8.x86_64/libntirpc/src/work_pool.c:183
#16 0x00007f713693f1ca in start_thread () from /lib64/libpthread.so.0
#17 0x00007f7136189e73 in clone () from /lib64/libc.so.6

**Comment by zhitaoli-6** [comment]
What is the meaning of "while running cthon in loop"?

**Comment by yogendra-t** [comment]
ran below command in for loop 100 times. issue seen after some runs.

./runcthon -a -f /test;
