### ISSUE TITLE
ganesha crash in Protocols/NFS/nfs3_create.c

### ISSUE THREAD

**Issue by yogendra-t** [nfs-ganesha/nfs-ganesha#1137]
Below crash is seen in 4.3:

(gdb) bt
#0  0x00007fff9f1c9a68 in raise () from /lib64/glibc-hwcaps/power9/libpthread-2.28.so
#1  0x00007fff9f7affb8 in crash_handler (signo=11, info=0x7fea6925d328, ctx=0x7fea6925c5b0)
    at /usr/src/debug/gpfs.nfs-ganesha-4.3-ibm073.14.el8.ppc64le/MainNFSD/nfs_init.c:244
#2  <signal handler called>
#3  0x00007fff9f8d8060 in nfs3_create_free (res=0x0) at /usr/src/debug/gpfs.nfs-ganesha-4.3-ibm073.14.el8.ppc64le/Protocols/NFS/nfs3_create.c:248
#4  0x00007fff9f7f33b0 in nfs_dupreq_rele (reqnfs=0x7fef85519ce0) at /usr/src/debug/gpfs.nfs-ganesha-4.3-ibm073.14.el8.ppc64le/RPCAL/nfs_dupreq.c:1417
#5  0x00007fff9f7a620c in free_args (reqdata=0x7fef85519ce0) at /usr/src/debug/gpfs.nfs-ganesha-4.3-ibm073.14.el8.ppc64le/MainNFSD/nfs_worker_thread.c:724
#6  0x00007fff9f7a9188 in nfs_rpc_process_request (reqdata=0x7fef85519ce0, retry=false)
    at /usr/src/debug/gpfs.nfs-ganesha-4.3-ibm073.14.el8.ppc64le/MainNFSD/nfs_worker_thread.c:1524
#7  0x00007fff9f7a98e4 in nfs_rpc_valid_NFS (req=0x7fef85519ce0) at /usr/src/debug/gpfs.nfs-ganesha-4.3-ibm073.14.el8.ppc64le/MainNFSD/nfs_worker_thread.c:1724
#8  0x00007fff9f6e0618 in svc_vc_decode (req=0x7fef85519ce0) at /usr/src/debug/gpfs.nfs-ganesha-4.3-ibm073.14.el8.ppc64le/libntirpc/src/svc_vc.c:913
#9  0x00007fff9f6da8f4 in svc_request (xprt=0x7fefc88245c0, xdrs=0x7fef84479f90)
    at /usr/src/debug/gpfs.nfs-ganesha-4.3-ibm073.14.el8.ppc64le/libntirpc/src/svc_rqst.c:1202
#10 0x00007fff9f6e04ac in svc_vc_recv (xprt=0x7fefc88245c0) at /usr/src/debug/gpfs.nfs-ganesha-4.3-ibm073.14.el8.ppc64le/libntirpc/src/svc_vc.c:886
#11 0x00007fff9f6da82c in svc_rqst_xprt_task_recv (wpe=0x7fefc88247f8) at /usr/src/debug/gpfs.nfs-ganesha-4.3-ibm073.14.el8.ppc64le/libntirpc/src/svc_rqst.c:1183
#12 0x00007fff9f6db858 in svc_rqst_epoll_loop (wpe=0x31ab7ea0) at /usr/src/debug/gpfs.nfs-ganesha-4.3-ibm073.14.el8.ppc64le/libntirpc/src/svc_rqst.c:1564
#13 0x00007fff9f6eb22c in work_pool_thread (arg=0x7ffdb08991b0) at /usr/src/debug/gpfs.nfs-ganesha-4.3-ibm073.14.el8.ppc64le/libntirpc/src/work_pool.c:183
#14 0x00007fff9f1b9678 in start_thread () from /lib64/glibc-hwcaps/power9/libpthread-2.28.so
#15 0x00007fff9f068938 in clone () from /lib64/glibc-hwcaps/power9/libc-2.28.so
(gdb) frame 3
**#3  0x00007fff9f8d8060 in nfs3_create_free (res=0x0) at /usr/src/debug/gpfs.nfs-ganesha-4.3-ibm073.14.el8.ppc64le/Protocols/NFS/nfs3_create.c:248**
warning: Source file is more recent than executable.
**248        if ((res->res_create3.status == NFS3_OK)
(gdb) p res
$1 = (nfs_res_t *) 0x0**

**Comment by ffilz** [comment]
Does this also occur on V5.x?

**Comment by yogendra-t** [comment]
yes, this issue seen in 5.x as well randomly

**Comment by ffilz** [comment]
OK, let's change the title then, upstream we not longer support 4.x, so we would fix this in V6 and back port to V5
