### ISSUE TITLE
ganesha crash while deleting lock_entry->sle_list in 4.3

### ISSUE THREAD

**Issue by yogendra-t** [nfs-ganesha/nfs-ganesha#1138]
Below is the backtrace of the crash. Crash occurring in  **glist_del(&lock_entry->sle_list);** as one of the sle is corrupt which might have been deleted already by another thread.

(gdb) bt 
#0  0x00007fff8ea79a68 in raise () from /lib64/glibc-hwcaps/power9/libpthread-2.28.so
#1  0x00007fff8f05ffb8 in crash_handler (signo=11, info=0x7fff892bd588, ctx=0x7fff892bc810)
    at /usr/src/debug/gpfs.nfs-ganesha-4.3-ibm073.14.el8.ppc64le/MainNFSD/nfs_init.c:244
#2  <signal handler called>
#3  0x00007fff8f0a85f0 in glist_del (node=0x7ff580badc60) at /usr/src/debug/gpfs.nfs-ganesha-4.3-ibm073.14.el8.ppc64le/include/gsh_list.h:102
#4  0x00007fff8f0abbac in remove_from_locklist (lock_entry=0x7ff580badc60) at /usr/src/debug/gpfs.nfs-ganesha-4.3-ibm073.14.el8.ppc64le/SAL/state_lock.c:737
#5  0x00007fff8f0ae960 in try_to_grant_lock (lock_entry=0x7ff580badc60) at /usr/src/debug/gpfs.nfs-ganesha-4.3-ibm073.14.el8.ppc64le/SAL/state_lock.c:1799
#6  0x00007fff8f0aeb34 in process_blocked_lock_upcall (block_data=0x7ff58091f970) at /usr/src/debug/gpfs.nfs-ganesha-4.3-ibm073.14.el8.ppc64le/SAL/state_lock.c:1816
#7  0x00007fff8f0a7490 in state_blocked_lock_caller (ctx=0x7ff740697600) at /usr/src/debug/gpfs.nfs-ganesha-4.3-ibm073.14.el8.ppc64le/SAL/state_async.c:82
#8  0x00007fff8f107d4c in fridgethr_start_routine (arg=0x7ff740697600) at /usr/src/debug/gpfs.nfs-ganesha-4.3-ibm073.14.el8.ppc64le/support/fridgethr.c:557
#9  0x00007fff8ea69678 in start_thread () from /lib64/glibc-hwcaps/power9/libpthread-2.28.so
#10 0x00007fff8e918938 in clone () from /lib64/glibc-hwcaps/power9/libc-2.28.so

**Comment by ffilz** [comment]
Does this also occur on V5.x?

**Comment by yogendra-t** [comment]
not sure, as it is reported by customer and no steps to recreate..

**Comment by ffilz** [comment]
Please check if it's possible there are any patches since V4.3 that might have fixed this.

Note that upstream we no longer support V4.x.
