### ISSUE TITLE
5.9: FileNotFoundError: [Errno 2] No such file or directory: 'dist/ganesha-top-5.9-py3-none-any.whl'

### ISSUE THREAD

**Issue by vt-alt** [nfs-ganesha/nfs-ganesha#1140]
When building 5.9 release the `ganesha-top` tool is not installed with the error (build on x86-64 Linux):
```
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/usr/lib/python3/site-packages/installer/__main__.py", line 98, in <module>
    _main(sys.argv[1:], "python -m installer")
  File "/usr/lib/python3/site-packages/installer/__main__.py", line 86, in _main
    with WheelFile.open(args.wheel) as source:
  File "/usr/lib64/python3.12/contextlib.py", line 137, in __enter__
    return next(self.gen)
           ^^^^^^^^^^^^^^
  File "/usr/lib/python3/site-packages/installer/sources.py", line 162, in open
    with zipfile.ZipFile(path) as f:
         ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.12/zipfile/__init__.py", line 1323, in __init__
    self.fp = io.open(file, filemode)
              ^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: 'dist/ganesha-top-5.9-py3-none-any.whl'
```
While actual file name is `dist/ganesha_top-5.9-py3-none-any.whl`.

```
$ grep ganesha.top build.log
02:07:25 [298/331] cd /usr/src/RPM/BUILD/nfs-ganesha-5.9/src/x86_64-alt-linux/scripts/ganesha-top && mkdir -p build/lib && echo ganesha-top && cp /usr/src/RPM/BUILD/nfs-ganesha-5.9/src/scripts/ganesha-top/ganesha-top.py ganesha-top
02:07:25 ganesha-top
02:07:26 [313/331] cd /usr/src/RPM/BUILD/nfs-ganesha-5.9/src/x86_64-alt-linux/scripts/ganesha-top && /usr/bin/python3.12 -m build --wheel --no-isolation . && /usr/bin/cmake -E touch /usr/src/RPM/BUILD/nfs-ganesha-5.9/src/x86_64-alt-linux/scripts/ganesha-top/build/ganesha_top_timestamp
02:07:26 Successfully built ganesha_top-5.9-py3-none-any.whl
reading sources... [100%] indexha-xfs-config
02:07:26 /usr/src/RPM/BUILD/nfs-ganesha-5.9/src/doc/man/ganesha-top.rst: WARNING: document isn't included in any toctree
02:07:26 ganesha-gluster-config.8 { } ganesha-gpfs-config.8 { } ganesha-kvsfs-config.8 { } ganesha-log-config.8 { } ganesha-lustre-config.8 { } ganesha-proxy-v3-config.8 { } ganesha-proxy-v4-config.8 { } ganesha-rados-cluster-design.8 { } ganesha-rados-grace.8 { } ganesha-rgw-config.8 { } ganesha-top.8 { } ganesha-vfs-config.8 { } ganesha-xfs-config.8 { } done
02:07:30 FileNotFoundError: [Errno 2] No such file or directory: 'dist/ganesha-top-5.9-py3-none-any.whl'
```

**Comment by vt-alt** [comment]
JFYI,
It seems Fedora just stopped packaging `ganesha-top` since 5.8. @kalebskeithley As you can see they have the same build failure: https://kojipkgs.fedoraproject.org/packages/nfs-ganesha/5.9/1.fc41/data/logs/x86_64/build.log

Obviously, this patch would fix the problem:
```diff
diff --git a/src/scripts/ganesha-top/CMakeLists.txt b/src/scripts/ganesha-top/CMakeLists.txt
--- a/src/scripts/ganesha-top/CMakeLists.txt
+++ b/src/scripts/ganesha-top/CMakeLists.txt
@@ -84,7 +84,7 @@ if(USE_ADMIN_TOOLS)
       install(
         CODE
         "execute_process(WORKING_DIRECTORY ${CMAKE_CURRENT_BINARY_DIR}
-        COMMAND ${Python3_EXECUTABLE} -m installer --destdir \$ENV{DESTDIR} dist/ganesha-top-${GANESHA_MAJOR_VERSION}${GANESHA_MINOR_VERSION}-py3-none-any.whl)"
+        COMMAND ${Python3_EXECUTABLE} -m installer --destdir \$ENV{DESTDIR} dist/ganesha_top-${GANESHA_MAJOR_VERSION}${GANESHA_MINOR_VERSION}-py3-none-any.whl)"
         )
     endif()
   endif(Python3_FOUND)
```

**Comment by xiaods** [comment]
so, this is bug on fedora upstream?

**Comment by vt-alt** [comment]
The bug, if this is a bug, perhaps, in `src/scripts/ganesha-top/CMakeLists.txt`.

[ps. Fedora (downstream) is just the example how this installation behavior caused `ganesha-top` already not being packaged in some distribution. And this proves this is not ALT specific build problem. You can ignore that reference to Fedora altogether. But I `@`-mentioned Fedora maintainer so he knows too about the issue.]

**Comment by ffilz** [comment]
Given the source directory is ganesha-top I would think we would want to make changes so ganesha-top is correct.
