### ISSUE TITLE
ganesha.nfsd crashed with ceph::__ceph_assert_fail

### ISSUE THREAD

**Issue by zhhuabj** [nfs-ganesha/nfs-ganesha#1157]
The ganesha.nfsd process is often terminated by a SIGABRT signal, with the following call trace:

(gdb) bt

#0 __pthread_kill_implementation (no_tid=0, signo=6, threadid=140705682900544) at ./nptl/pthread_kill.c:44

#1 __pthread_kill_internal (signo=6, threadid=140705682900544) at ./nptl/pthread_kill.c:78

#2 __GI___pthread_kill (threadid=140705682900544, signo=signo@entry=6) at ./nptl/pthread_kill.c:89

#3 0x00007ffa92094476 in __GI_raise (sig=sig@entry=6) at ../sysdeps/posix/raise.c:26

#4 0x00007ffa9207a7f3 in __GI_abort () at ./stdlib/abort.c:79

#5 0x00007ffa910783c3 in ceph::__ceph_assert_fail (assertion=<optimized out>, file=<optimized out>, line=<optimized out>, func=<optimized out>) at ./src/common/assert.cc:75

#6 0x00007ffa91078525 in ceph::__ceph_assert_fail (ctx=...) at ./src/common/assert.cc:80

#7 0x00007ffa7049f602 in xlist<ObjectCacher::Object*>::size (this=0x7ffa20734638, this=0x7ffa20734638) at ./src/include/xlist.h:87

#8 operator<< (os=..., out=warning: RTTI symbol not found for class 'StackStringStream<4096ul>'

...) at ./src/osdc/ObjectCacher.h:760

#9 operator<< (out=warning: RTTI symbol not found for class 'StackStringStream<4096ul>'

..., in=...) at ./src/client/Inode.cc:80

#10 0x00007ffa7045545f in Client::ll_sync_inode (this=0x55958b8a5c60, in=in@entry=0x7ffa20734270, syncdataonly=syncdataonly@entry=false) at ./src/client/Client.cc:14717

#11 0x00007ffa703d0f75 in ceph_ll_sync_inode (cmount=cmount@entry=0x55958b0bd0d0, in=in@entry=0x7ffa20734270, syncdataonly=syncdataonly@entry=0) at ./src/libcephfs.cc:1865

#12 0x00007ffa9050ddc5 in fsal_ceph_ll_setattr (creds=<optimized out>, mask=<optimized out>, stx=0x7ff8983f25a0, i=<optimized out>, cmount=<optimized out>)

  at ./src/FSAL/FSAL_CEPH/statx_compat.h:209

#13 ceph_fsal_setattr2 (obj_hdl=0x7fecc8fefbe0, bypass=<optimized out>, state=<optimized out>, attrib_set=0x7ff8983f2830) at ./src/FSAL/FSAL_CEPH/handle.c:2410

#14 0x00007ffa92371da0 in mdcache_setattr2 (obj_hdl=0x7fecc9e98778, bypass=<optimized out>, state=0x7fef0d64c9b0, attrs=0x7ff8983f2830)

  at ../FSAL/Stackable_FSALs/FSAL_MDCACHE/./src/FSAL/Stackable_FSALs/FSAL_MDCACHE/mdcache_handle.c:1012

#15 0x00007ffa922b2bbc in fsal_setattr (obj=0x7fecc9e98778, bypass=<optimized out>, state=0x7fef0d64c9b0, attr=0x7ff8983f2830) at ./src/FSAL/fsal_helper.c:573

#16 0x00007ffa9234c7bd in nfs4_op_setattr (op=0x7fecad7ac510, data=0x7fecac314a10, resp=0x7fecad1be200) at ../Protocols/NFS/./src/Protocols/NFS/nfs4_op_setattr.c:212

#17 0x00007ffa9232e413 in process_one_op (data=data@entry=0x7fecac314a10, status=status@entry=0x7ff8983f2a2c) at ../Protocols/NFS/./src/Protocols/NFS/nfs4_Compound.c:920

#18 0x00007ffa9232f9e0 in nfs4_Compound (arg=<optimized out>, req=0x7fecad491620, res=0x7fecac054580) at ../Protocols/NFS/./src/Protocols/NFS/nfs4_Compound.c:1327

#19 0x00007ffa922cb0ff in nfs_rpc_process_request (reqdata=0x7fecad491620) at ./src/MainNFSD/nfs_worker_thread.c:1508

#20 0x00007ffa92029be7 in svc_request (xprt=0x7fed640504d0, xdrs=<optimized out>) at ./src/svc_rqst.c:1202

#21 0x00007ffa9202df9a in svc_rqst_xprt_task_recv (wpe=<optimized out>) at ./src/svc_rqst.c:1183

#22 0x00007ffa9203344d in svc_rqst_epoll_loop (wpe=0x559594308e60) at ./src/svc_rqst.c:1564

#23 0x00007ffa920389e1 in work_pool_thread (arg=0x7feeb802ea10) at ./src/work_pool.c:184

#24 0x00007ffa920e6b43 in start_thread (arg=<optimized out>) at ./nptl/pthread_create.c:442

#25 0x00007ffa92178a00 in clone3 () at ../sysdeps/unix/sysv/linux/x86_64/clone3.S:81

Not sure under what circumstances a crash can be triggered, the version info is as follows.

$ grep -E 'ceph|ganesha' sos_commands/dpkg/dpkg_-l
ii  ceph-common                          17.2.5-0ubuntu0.22.04.3                         amd64        common utilities to mount and interact with a ceph storage cluster
ii  libcephfs2                           17.2.5-0ubuntu0.22.04.3                         amd64        Ceph distributed file system client library
ii  nfs-ganesha                          3.5-1ubuntu1                                    amd64        NFS server in User Space
ii  nfs-ganesha-ceph:amd64               3.5-1ubuntu1                                    amd64        nfs-ganesha fsal ceph libraries
ii  python3-ceph-argparse                17.2.5-0ubuntu0.22.04.3                         amd64        Python 3 utility libraries for Ceph CLI
ii  python3-ceph-common                  17.2.5-0ubuntu0.22.04.3                         all          Python 3 utility libraries for Ceph
ii  python3-cephfs                       17.2.5-0ubuntu0.22.04.3                         amd64        Python 3 libraries for the Ceph libcephfs library

More crash info can be found here - https://paste.ubuntu.com/p/tV4NRC67Yn/

**Comment by tianjicaoyuan** [comment]
你这个可以复现吗？

**Comment by tianjicaoyuan** [comment]
can you reproduce it？

**Comment by ffilz** [comment]
I think this is a Ceph bug not a Ganesha bug. Or at least it needs to be explored in Ceph first.

**Comment by sachinpunadikar** [comment]
This is found to be an issue of caching dirents in Ganesha. The cached info is incorrect due to cache size differences between Ganesha cache (basically MDCACHE) and ceph client cache.
Please try out with below settings in ganesha.conf file 
For disabling mdcache dirent caching, use below settings in ganesha.conf file 

         MDCACHE {
            Dir_Chunk = 0;
         }
 
         EXPORT_DEFAULTS {
            Attr_Expiration_Time = 0;
         }

**Comment by chengzhidada** [comment]
> This is found to be an issue of caching dirents in Ganesha. The cached info is incorrect due to cache size differences between Ganesha cache (basically MDCACHE) and ceph client cache. Please try out with below settings in ganesha.conf file For disabling mdcache dirent caching, use below settings in ganesha.conf file
> 
> ```
>      MDCACHE {
>         Dir_Chunk = 0;
>      }
> 
>      EXPORT_DEFAULTS {
>         Attr_Expiration_Time = 0;
>      }
> ```

Hi,Bro! I'm also experiencing this issue, but it occurs randomly and I can't reproduce it. Could you please reproduce it? Also, could you explain the issue in more detail?

**Comment by ffilz** [comment]
Closing as not a Ganesha issue.
