### ISSUE TITLE
V6-dev.20 segfault on start only when -N NIV_DEBUG

### ISSUE THREAD

**Issue by mkogan1** [nfs-ganesha/nfs-ganesha#1168]
repro occurs on start (without any load)
```
❯ sudo rm ./ganesha.log ; sudo numactl -N 0 -m 0 -- sh -c "ulimit -n 10485760 ; env TCMALLOC_MAX_TOTAL_THREAD_CACHE_BYTES=134217728 gdb --args ./ganesha.nfsd -L ./ganesha.log -N NIV_DEBUG -F"

(gdb) r                                                                                                                                                                                      
Starting program: /home/mkogan/src-git/nfs-ganesha-perf/build/ganesha.nfsd -L ./ganesha.log -N NIV_DEBUG -F                                                                                  
[Thread debugging using libthread_db enabled]                                                                                                                                                
Using host libthread_db library "/lib64/libthread_db.so.1".
[New Thread 0x7ffff69ff640 (LWP 3834629)]
[New Thread 0x7ffff61fe640 (LWP 3834631)]
...
Thread 14 "ganesha.nfsd" received signal SIGSEGV, Segmentation fault.
[Switching to Thread 0x7ffff09f3640 (LWP 3834668)]
0x00007ffff756e57c in __strlen_evex () from /lib64/libc.so.6
Missing separate debuginfos, use: dnf debuginfo-install glibc-2.34-100.el9_4.2.x86_64 gperftools-libs-2.9.1-2.el9.x86_64 gssproxy-0.8.4-6.el9.x86_64 keyutils-libs-1.6.3-1.el9.x86_64 krb5-libs-1.21.1-1.el9.x86_64 libacl-2.3.1-4.el9.x86_64 libattr-2.5.1-3.el9.x86_64 libblkid-2.37.4-18.el9.x86_64 libcom_err-1.46.5-5.el9.x86_64 libibverbs-46.0-1.el9.x86_64 libnl3-3.7.0-1.el9.x86_64 libnsl2-2.0.0-1.el9.x86_64 librdmacm-46.0-1.el9.x86_64 libselinux-3.6-1.el9.x86_64 libstdc++-11.4.1-3.el9.x86_64 libtirpc-1.3.3-2.el9.x86_64 libunwind-1.6.2-1.el9.x86_64 libuuid-2.37.4-18.el9.x86_64 openssl-libs-3.0.7-24.el9.x86_64 sssd-client-2.9.4-6.el9_4.x86_64 userspace-rcu-0.12.1-6.el9.x86_64 zlib-1.2.11-40.el9.x86_64
(gdb) bt
#0  0x00007ffff756e57c in __strlen_evex () from /lib64/libc.so.6
#1  0x00007ffff746e6b8 in __vfprintf_internal () from /lib64/libc.so.6
#2  0x00007ffff747ecca in __vsnprintf_internal () from /lib64/libc.so.6
#3  0x00007ffff7ca96fc in vsnprintf (__ap=0x0, __fmt=0x1a4 <error: Cannot access memory at address 0x1a4>, __n=1919, __s=<optimized out>) at /usr/include/bits/stdio2.h:68
#4  display_vprintf (dspbuf=dspbuf@entry=0x7ffff09f1c30, fmt=fmt@entry=0x7ffff7e21eb8 "%s: fd %d: Connection is not managed by connection manager", args=args@entry=0x7ffff09f1ca0)
    at /home/mkogan/src-git/nfs-ganesha-perf/src/log/display.c:311
#5  0x00007ffff7cab935 in display_log_component_level (component=COMPONENT_XPRT, file=<optimized out>, line=538, 
    function=0x7ffff7e22120 <__func__.2> "connection_manager__connection_started", level=NIV_DEBUG, format=0x7ffff7e21eb8 "%s: fd %d: Connection is not managed by connection manager", 
    arguments=0x7ffff09f1ca0) at /home/mkogan/src-git/nfs-ganesha-perf/src/log/log_functions.c:1456
#6  0x00007ffff7cac1ea in DisplayLogComponentLevel (component=component@entry=COMPONENT_XPRT, 
    file=file@entry=0x7ffff7e21ac8 "/home/mkogan/src-git/nfs-ganesha-perf/src/RPCAL/connection_manager.c", line=line@entry=538, 
    function=function@entry=0x7ffff7e22120 <__func__.2> "connection_manager__connection_started", level=level@entry=NIV_DEBUG, 
    format=format@entry=0x7ffff7e21eb8 "%s: fd %d: Connection is not managed by connection manager") at /home/mkogan/src-git/nfs-ganesha-perf/src/log/log_functions.c:1658
#7  0x00007ffff7cb2c70 in connection_manager__connection_started (xprt=xprt@entry=0x8ba5180) at /home/mkogan/src-git/nfs-ganesha-perf/src/RPCAL/connection_manager.c:538
#8  0x00007ffff7c6ce4d in nfs_rpc_dispatch_remote_addr_set_tcp (xprt=0x8ba5180) at /home/mkogan/src-git/nfs-ganesha-perf/src/MainNFSD/nfs_rpc_dispatcher_thread.c:429
#9  0x00007ffff7f774bf in update_and_notify_remote_address_set (xprt=0x8ba5180) at /home/mkogan/src-git/nfs-ganesha-perf/src/libntirpc/src/svc_vc.c:752
#10 0x00007ffff7f79967 in svc_vc_recv (xprt=0x8ba5180) at /home/mkogan/src-git/nfs-ganesha-perf/src/libntirpc/src/svc_vc.c:1154
#11 0x00007ffff7f71113 in svc_rqst_xprt_task_recv (wpe=<optimized out>) at /home/mkogan/src-git/nfs-ganesha-perf/src/libntirpc/src/svc_rqst.c:1210
#12 0x00007ffff7f72079 in svc_rqst_epoll_loop (wpe=0x8b70118) at /home/mkogan/src-git/nfs-ganesha-perf/src/libntirpc/src/svc_rqst.c:1585
#13 0x00007ffff7f86820 in work_pool_thread (arg=0x5ce4870) at /home/mkogan/src-git/nfs-ganesha-perf/src/libntirpc/src/work_pool.c:187
#14 0x00007ffff7489c02 in start_thread () from /lib64/libc.so.6
#15 0x00007ffff750ec40 in clone3 () from /lib64/libc.so.6
(gdb) 

```

**Comment by mkogan1** [comment]
(note: there is mount that probably automatically re-connects)

**Comment by mkogan1** [comment]
https://review.gerrithub.io/c/ffilz/nfs-ganesha/+/1199899 solves the NIV_DEBUG segf
