### ISSUE TITLE
crash in mdcache_avl_remove()->gsh_free() in Ganesha 5.7

### ISSUE THREAD

**Issue by yogendra-t** [nfs-ganesha/nfs-ganesha#1183]
Ganesha crash found in 5.7 and below is the backtrace of the crash .

(gdb) bt
#0  0x00007f75a4520bbf in raise () from /lib64/libpthread.so.0
#1  0x00007f75a6428b94 in crash_handler (signo=6, info=0x7f72f5edbaf0, ctx=0x7f72f5edb9c0)
    at /usr/src/debug/gpfs.nfs-ganesha-5.7-ibm022.00.el8.x86_64/MainNFSD/nfs_init.c:256
#2  <signal handler called>
#3  0x00007f75a3d6452f in raise () from /lib64/libc.so.6
#4  0x00007f75a3d37e65 in abort () from /lib64/libc.so.6
#5  0x00007f75a3da5727 in __libc_message () from /lib64/libc.so.6
#6  0x00007f75a3daca2c in malloc_printerr () from /lib64/libc.so.6
#7  0x00007f75a3daeabc in _int_free () from /lib64/libc.so.6
#8  0x00007f75a654e956 in gsh_free (p=0x7f72345f9b20) at /usr/src/debug/gpfs.nfs-ganesha-5.7-ibm022.00.el8.x86_64/include/abstract_mem.h:257
#9  0x00007f75a654f866 in mdcache_avl_remove (parent=0x7f7164655d30, dirent=0x7f72345f9b20)
    at /usr/src/debug/gpfs.nfs-ganesha-5.7-ibm022.00.el8.x86_64/FSAL/Stackable_FSALs/FSAL_MDCACHE/mdcache_avl.c:245
#10 0x00007f75a65509ab in mdcache_avl_clean_trees (parent=0x7f7164655d30)
    at /usr/src/debug/gpfs.nfs-ganesha-5.7-ibm022.00.el8.x86_64/FSAL/Stackable_FSALs/FSAL_MDCACHE/mdcache_avl.c:615
#11 0x00007f75a653b902 in mdcache_dirent_invalidate_all (entry=0x7f7164655d30)
    at /usr/src/debug/gpfs.nfs-ganesha-5.7-ibm022.00.el8.x86_64/FSAL/Stackable_FSALs/FSAL_MDCACHE/mdcache_helpers.c:632
#12 0x00007f75a652d237 in mdcache_refresh_attrs (entry=0x7f7164655d30, need_acl=false, need_fslocations=false, need_seclabel=false, invalidate=true)
    at /usr/src/debug/gpfs.nfs-ganesha-5.7-ibm022.00.el8.x86_64/FSAL/Stackable_FSALs/FSAL_MDCACHE/mdcache_handle.c:937
#13 0x00007f75a652d713 in mdcache_getattrs (obj_hdl=0x7f7164655d68, attrs_out=0x7f72f5edcd50)
    at /usr/src/debug/gpfs.nfs-ganesha-5.7-ibm022.00.el8.x86_64/FSAL/Stackable_FSALs/FSAL_MDCACHE/mdcache_handle.c:993
#14 0x00007f75a6507fa3 in nfs_SetPostOpAttr (obj=0x7f7164655d68, Fattr=0x7f72345f9c28, attrs=0x0)
    at /usr/src/debug/gpfs.nfs-ganesha-5.7-ibm022.00.el8.x86_64/Protocols/NFS/nfs_proto_tools.c:88
#15 0x00007f75a650828b in nfs_SetWccData (before_attr=0x7f72f5edd000, obj=0x7f7164655d68, wcc_data=0x7f72345f9c08)
    at /usr/src/debug/gpfs.nfs-ganesha-5.7-ibm022.00.el8.x86_64/Protocols/NFS/nfs_proto_tools.c:161
#16 0x00007f75a6517f0c in nfs3_remove (arg=0x7f72345f3f50, req=0x7f72345f3720, res=0x7f72345f9c00)
    at /usr/src/debug/gpfs.nfs-ganesha-5.7-ibm022.00.el8.x86_64/Protocols/NFS/nfs3_remove.c:134
#17 0x00007f75a6423bec in nfs_rpc_process_request (reqdata=0x7f72345f3720, retry=false)
    at /usr/src/debug/gpfs.nfs-ganesha-5.7-ibm022.00.el8.x86_64/MainNFSD/nfs_worker_thread.c:1559
#18 0x00007f75a6424189 in nfs_rpc_valid_NFS (req=0x7f72345f3720) at /usr/src/debug/gpfs.nfs-ganesha-5.7-ibm022.00.el8.x86_64/MainNFSD/nfs_worker_thread.c:1784
#19 0x00007f75a619a8c4 in svc_vc_decode (req=0x7f72345f3720) at /usr/src/debug/gpfs.nfs-ganesha-5.7-ibm022.00.el8.x86_64/libntirpc/src/svc_vc.c:1046
#20 0x00007f75a6195de2 in svc_request (xprt=0x7f742400da00, xdrs=0x7f72345eda70)
    at /usr/src/debug/gpfs.nfs-ganesha-5.7-ibm022.00.el8.x86_64/libntirpc/src/svc_rqst.c:1202
#21 0x00007f75a619a7c9 in svc_vc_recv (xprt=0x7f742400da00) at /usr/src/debug/gpfs.nfs-ganesha-5.7-ibm022.00.el8.x86_64/libntirpc/src/svc_vc.c:1019
#22 0x00007f75a6195d62 in svc_rqst_xprt_task_recv (wpe=0x7f742400dcc8) at /usr/src/debug/gpfs.nfs-ganesha-5.7-ibm022.00.el8.x86_64/libntirpc/src/svc_rqst.c:1183
#23 0x00007f75a61968f6 in svc_rqst_epoll_loop (wpe=0x20f9ae8) at /usr/src/debug/gpfs.nfs-ganesha-5.7-ibm022.00.el8.x86_64/libntirpc/src/svc_rqst.c:1564
#24 0x00007f75a61a1dbd in work_pool_thread (arg=0x7f7500926790) at /usr/src/debug/gpfs.nfs-ganesha-5.7-ibm022.00.el8.x86_64/libntirpc/src/work_pool.c:183
#25 0x00007f75a45161ca in start_thread () from /lib64/libpthread.so.0
#26 0x00007f75a3d4f8d3 in clone () from /lib64/libc.so.6

**Comment by ffilz** [comment]
Can you easily recreate this? It would be worth seeing if it recreates in V6.1.

**Comment by ffilz** [comment]
If this is really still an issue, we need an issue in some other tracker. Upstream github is not the right place for issues with old Ganesha versions no longer supported upstream.
