### ISSUE TITLE
Ganesha crash in free_delegrecall_context after deleg_revoke

### ISSUE THREAD

**Issue by xueqianhu47** [nfs-ganesha/nfs-ganesha#1195]
When running delegation workload test, we recently hit crash in:
(gdb) bt
#0  0x00007f9c96047bbf in raise () from /lib64/libpthread.so.0
#1  0x00007f9c983d0146 in crash_handler (signo=6, info=0x7f9c8249a930, ctx=0x7f9c8249a800) at /usr/src/debug/nfs-ganesha-5.5.3-0.1.nutanix.722755fe5.el8.x86_64/MainNFSD/nfs_init.c:275
#2  <signal handler called>
#3  0x00007f9c9588b52f in raise () from /lib64/libc.so.6
#4  0x00007f9c9585ee65 in abort () from /lib64/libc.so.6
#5  0x00007f9c983a5d25 in free_delegrecall_context (deleg_ctx=0x7f9c830c7860) at /usr/src/debug/nfs-ganesha-5.5.3-0.1.nutanix.722755fe5.el8.x86_64/FSAL_UP/fsal_up_top.c:1066
#6  0x00007f9c983a6dfc in delegrecall_one (obj=0x7f9c6efd6038, state=0x7f9c87bf5600, p_cargs=0x7f9c830c7860) at /usr/src/debug/nfs-ganesha-5.5.3-0.1.nutanix.722755fe5.el8.x86_64/FSAL_UP/fsal_up_top.c:1313
#7  0x00007f9c983a77b1 in delegrecall_task (ctx=0x7f9c830c7860) at /usr/src/debug/nfs-ganesha-5.5.3-0.1.nutanix.722755fe5.el8.x86_64/FSAL_UP/fsal_up_top.c:1439
#8  0x00007f9c98474217 in delayed_thread (arg=0x7f9c892015a0) at /usr/src/debug/nfs-ganesha-5.5.3-0.1.nutanix.722755fe5.el8.x86_64/support/delayed_exec.c:241
#9  0x00007f9c9603d1ca in start_thread () from /lib64/libpthread.so.0
#10 0x00007f9c958768d3 in clone () from /lib64/libc.so.6

From ganesha log, we could see that crash happened after revoking delegation:
16/10/2024 17:26:43Z : vm1 82175[none] [Async] delegrecall_one :STATE :CRIT :Delegation will be revoked for STATE 0x7f9c87bf5600 OTHER=0x370300009ff1560002000000 {{CLIENTID Epoch=0x0056f19f Counter=0x00000337} StateIdCounter=0x00000002} obj=0x7f9c6efd6038 type=DELEGATION seqid=1 owner={STATE_CLIENTID_OWNER_NFSV4 0x7f9c6fe26fc0: clientid={0x7f9c6fe26c00 ClientID={Epoch=0x0056f19f Counter=0x000003e0} EXPIRED ClientRec={0x7f9c85410700 name=(25:Linux NFSv4.1 nfs-deleg11) cr_refcount=30} t_delta=182 reservations=0 cid_refcount=1 files_opened=0,} owner=(NULL) confirmed=0 seqid=0 so_refcount=1} st_refcount=2
16/10/2024 17:26:43Z : vm1 82175[none] [Async] free_delegrecall_context :RW LOCK :CRIT :Error 22, acquiring mutex 0x7f9c6fe26d80 (&deleg_ctx->drc_clid->cid_mutex) at /home/jenkins/nfs-ganesha/build.9b65c09ab/rpmbuild/BUILD/nfs-ganesha-5.5.3/FSAL_UP/fsal_up_top.c:1066
16/10/2024 17:26:43Z : vm1 82175[none] [Async] gsh_libunwind :NFS STARTUP :MAJ :BACKTRACE:
 #0 gsh_libunwind + 0x2f [ip=0x7f9c98407d57] [sp=0x7f9c82499da0]
 #1 crash_handler + 0x26 [ip=0x7f9c983d013c] [sp=0x7f9c8249a7d0]
 #2 funlockfile + 0x50 [ip=0x7f9c96047d20] [sp=0x7f9c8249a800]
 #3 gsignal + 0x10f [ip=0x7f9c9588b52f] [sp=0x7f9c8249ada0]
 #4 abort + 0x127 [ip=0x7f9c9585ee65] [sp=0x7f9c8249aec0]
 #5 free_delegrecall_context + 0x138 [ip=0x7f9c983a5d25] [sp=0x7f9c8249aff0]
 #6 delegrecall_one + 0x549 [ip=0x7f9c983a6dfc] [sp=0x7f9c8249b020]
 #7 delegrecall_task + 0x2cc [ip=0x7f9c983a77b1] [sp=0x7f9c8249b8f0]

The direct reason for the crash is ganesha accessing lock already been destroyed and the cid_refcount is 0 that time(the client was EXPIRED).
From above log, interesting thing here is the refcount, the before revoking, client's cid_refcount was 1 and the owner's so_refcount was 1. 
But deleg_revoke will increase so_refcount once but decrease it twice:
(1)inc "deleg_revoke -> get_state_obj_export_owner_refs"
(2)dec 1:"deleg_revoke -> _state_del_locked -> dec_state_owner_ref"
(3)dec 2 "deleg_revoke -> dec_state_owner_ref"
So, in (3) so_refcount will be decreased to 0 & "dec_state_owner_ref -> free_state_owner -> free_nfs4_owner -> dec_client_id_ref" will decrease the cid_refcount to 0(and destroy the lock).

Do we expect in this case, the so_refcount to be 1 & cid_refcount to also be 1 in delegrecall_one?

**Comment by ffilz** [comment]
@s-athani could you look at this?
