### ISSUE TITLE
nfs-ganesha server crash with message "malloc(): unaligned tcache chunk detected"

### ISSUE THREAD

**Issue by vklonghml** [nfs-ganesha/nfs-ganesha#1212]
os: centos 9
podman version: 5.2.3
ganesha nfs version: NFS-Ganesha Release = V5.5
when write data into nfs share folder, the nfs-ganesha server crash with below log:

17/12/2024 07:00:50 : epoch 67612140 : ceph-node01 : ganesha.nfsd-2[svc_7] get_gsh_export :EXPORT :DEBUG :Found Export 1 pseudo (/cephfs/volumes/ec-subgrp01/other-write/794200f6-f78a-4dae-a315-d0ef6267a0c1) with path (/volumes/ec-subgrp01/other-write/794200f6-f78a-4dae-a315-d0ef6267a0c1) and tag ((null)) perms (options=03203002/077801e7 root_squash , ----, -4-, UDP, TCP, ----, , , , , expire= 0)
17/12/2024 07:00:50 : epoch 67612140 : ceph-node01 : ganesha.nfsd-2[svc_7] nfs4_mds_putfh :EXPORT :DEBUG :PUTFH Export 1 pseudo (/cephfs/volumes/ec-subgrp01/other-write/794200f6-f78a-4dae-a315-d0ef6267a0c1) with path (/volumes/ec-subgrp01/other-write/794200f6-f78a-4dae-a315-d0ef6267a0c1) and tag ((null)) perms (options=03203002/077801e7 root_squash , ----, -4-, UDP, TCP, ----, , , , , expire= 0)
17/12/2024 07:00:50 : epoch 67612140 : ceph-node01 : ganesha.nfsd-2[svc_7] cih_get_by_key_latch :HT CACHE :DEBUG :cih cache hit slot 619
17/12/2024 07:00:50 : epoch 67612140 : ceph-node01 : ganesha.nfsd-2[svc_7] complete_op :NFS4 :DEBUG :Status of OP_PUTFH in position 0 = NFS4_OK, op response size is 4 total response size is 40
17/12/2024 07:00:50 : epoch 67612140 : ceph-node01 : ganesha.nfsd-2[svc_7] process_one_op :NFS4 :DEBUG :Request 1: opcode 9 is OP_GETATTR
17/12/2024 07:00:50 : epoch 67612140 : ceph-node01 : ganesha.nfsd-2[svc_7] file_To_Fattr :NFS4 ACL :DEBUG :No permission check for ACL for obj 0x7f2d5c02dce8
17/12/2024 07:00:50 : epoch 67612140 : ceph-node01 : ganesha.nfsd-2[svc_7] encode_fsid :NFS4 :DEBUG :fsid.major = 4294967295, fsid.minor = 4294967294
17/12/2024 07:00:50 : epoch 67612140 : ceph-node01 : ganesha.nfsd-2[svc_7] complete_op :NFS4 :DEBUG :Status of OP_GETATTR in position 1 = NFS4_OK, op response size is 152 total response size is 196
17/12/2024 07:00:50 : epoch 67612140 : ceph-node01 : ganesha.nfsd-2[svc_7] process_one_op :NFS4 :DEBUG :Request 2: opcode 12 is OP_LOCK
17/12/2024 07:00:50 : epoch 67612140 : ceph-node01 : ganesha.nfsd-2[svc_7] nfs4_op_lock :NFS4 LOCK :DEBUG :Entering NFS v4 LOCK handler ----------------------
malloc(): unaligned tcache chunk detected

**Comment by MariusSchiffer** [comment]
I have the same error on v4.3 (Proxmox), here's a further stacktrace:

```
#6  0x00007ffff7c93bec in tcache_get (tc_idx=<optimized out>) at ./malloc/malloc.c:3189
#7  __GI___libc_malloc (bytes=bytes@entry=13) at ./malloc/malloc.c:3307
#8  0x00007ffff7eb9c14 in nfs4_Compound (arg=0x7fff9c00e148, req=0x7fff9c00d920, res=0x7fff9c00cf70) at ./src/Protocols/NFS/nfs4_Compound.c:1250
#9  0x00007ffff7e36d33 in nfs_rpc_process_request (reqdata=0x7fff9c00d920, retry=<optimized out>) at ./src/MainNFSD/nfs_worker_thread.c:1499
#10 0x00007ffff7bd8dbc in svc_request (xprt=0x7fff9c000e10, xdrs=<optimized out>) at ./src/svc_rqst.c:1202
#11 0x00007ffff7bd65e1 in svc_rqst_xprt_task_recv (wpe=<optimized out>) at ./src/svc_rqst.c:1183
#12 0x00007ffff7bd7030 in svc_rqst_epoll_loop (wpe=0x555558a23938) at ./src/svc_rqst.c:1564
#13 0x00007ffff7be1d05 in work_pool_thread (arg=0x7fff68005550) at ./src/work_pool.c:183
#14 0x00007ffff7c841c4 in start_thread (arg=<optimized out>) at ./nptl/pthread_create.c:442
#15 0x00007ffff7d0485c in clone3 () at ../sysdeps/unix/sysv/linux/x86_64/clone3.S:81
```

I'll test out a later version

**Comment by ffilz** [comment]
Testing on V6.5 would be much appreciated.

**Comment by ffilz** [comment]
Closing for lack of a response in over a year.
