### ISSUE TITLE
SIGSEGV when client connects

### ISSUE THREAD

**Issue by JoelStienlet** [nfs-ganesha/nfs-ganesha#298]
Hello!
I got a segmentation fault, happening each time the client tries to mount the volume.

-> command line on the server:
sudo gdb --args /usr/local/bin/ganesha.nfsd -p /home/stienlet/ganesha_pid_file -F -L /home/stienlet/ganesha_debug_log.txt

-> source version: e34c16d4bed9037c46c4675696cfe31da1d17604

-> built on fedora 28 using:
cmake -DUSE_GSS=OFF -DUSE_NLM=OFF -DUSE_FSAL_CEPH=OFF -DUSE_FSAL_GLUSTER=OFF -DUSE_FSAL_GPFS=OFF -DUSE_FSAL_LUSTRE=OFF -DUSE_FSAL_MEM=OFF -DUSE_FSAL_NULL=OFF -DUSE_FSAL_PANFS=OFF -DUSE_FSAL_PROXY=OFF -DUSE_FSAL_RGW=OFF -DUSE_FSAL_XFS=OFF -DUSE_GUI_ADMIN_TOOLS=OFF  -DUSE_NFS3=OFF -DUSE_RADOS_RECOV=OFF -D_MSPAC_SUPPORT=OFF -DUSE_DBUS=OFF -DUSE_9P=OFF -DTIRPC_EPOLL=ON -DRPCBIND=OFF -DSYSCONFDIR:PATH=/home/nfs/etc -DSYSSTATEDIR:PATH=/home/nfs/var

gdb output:

Thread 15 "ganesha.nfsd" received signal SIGSEGV, Segmentation fault.
[Switching to LWP 32167]
0x00007ffff7231b7d in free () from /lib64/libc.so.6
Missing separate debuginfos, use: dnf debuginfo-install keyutils-libs-1.5.10-6.fc28.x86_64 krb5-libs-1.16.1-2.fc28.x86_64 libcom_err-1.43.8-2.fc28.x86_64 libnsl2-1.2.0-1.fc28.x86_64 libntirpc-1.6.2-1.fc28.x86_64 libselinux-2.7-13.fc28.x86_64 openssl-libs-1.1.0h-3.fc28.x86_64 pcre2-10.31-4.fc28.x86_64 zlib-1.2.11-8.fc28.x86_64
(gdb) bt
#0  0x00007ffff7231b7d in free () from /lib64/libc.so.6
#1  0x0000000000439a5c in gsh_free_size (p=0xe5, n=0) at /home/stienlet/ganesha/nfs-ganesha/src/include/abstract_mem.h:287
#2  0x00007ffff7593a63 in xdr_array () from /lib64/libntirpc.so.1.6
#3  0x00007ffff7574a92 in xdr_authunix_parms () from /lib64/libntirpc.so.1.6
#4  0x0000000000446f94 in xdr_callback_sec_parms4 (xdrs=0x7870a0 <xdr_free_null_stream@@NTIRPC_1.6.2>, objp=0x7fffc4001a30) at /home/stienlet/ganesha/nfs-ganesha/src/include/nfsv41.h:6756
#5  0x0000000000442692 in xdr_array_free (xdrs=0x7870a0 <xdr_free_null_stream@@NTIRPC_1.6.2>, cpp=0x7fffc4001a08, sizep=0x7fffc4001a00, maxsize=1024, selem=40, xdr_elem=0x446f3d <xdr_callback_sec_parms4>)
    at /home/stienlet/ganesha/nfs-ganesha/src/libntirpc/ntirpc/rpc/xdr_inline.h:872
#6  0x0000000000442783 in xdr_array (xdrs=0x7870a0 <xdr_free_null_stream@@NTIRPC_1.6.2>, cpp=0x7fffc4001a08, sizep=0x7fffc4001a00, maxsize=1024, selem=40, xdr_elem=0x446f3d <xdr_callback_sec_parms4>)
    at /home/stienlet/ganesha/nfs-ganesha/src/libntirpc/ntirpc/rpc/xdr_inline.h:894
#7  0x0000000000447afb in xdr_CREATE_SESSION4args (xdrs=0x7870a0 <xdr_free_null_stream@@NTIRPC_1.6.2>, objp=0x7fffc4001998) at /home/stienlet/ganesha/nfs-ganesha/src/include/nfsv41.h:7049
#8  0x000000000044a8d9 in xdr_nfs_argop4 (xdrs=0x7870a0 <xdr_free_null_stream@@NTIRPC_1.6.2>, objp=0x7fffc4001990) at /home/stienlet/ganesha/nfs-ganesha/src/include/nfsv41.h:8233
#9  0x0000000000442692 in xdr_array_free (xdrs=0x7870a0 <xdr_free_null_stream@@NTIRPC_1.6.2>, cpp=0x7fffc4001908, sizep=0x7fffc4001900, maxsize=1024, selem=144, xdr_elem=0x449e03 <xdr_nfs_argop4>)
    at /home/stienlet/ganesha/nfs-ganesha/src/libntirpc/ntirpc/rpc/xdr_inline.h:872
#10 0x0000000000442783 in xdr_array (xdrs=0x7870a0 <xdr_free_null_stream@@NTIRPC_1.6.2>, cpp=0x7fffc4001908, sizep=0x7fffc4001900, maxsize=1024, selem=144, xdr_elem=0x449e03 <xdr_nfs_argop4>)
    at /home/stienlet/ganesha/nfs-ganesha/src/libntirpc/ntirpc/rpc/xdr_inline.h:894
#11 0x000000000044bf79 in xdr_COMPOUND4args (xdrs=0x7870a0 <xdr_free_null_stream@@NTIRPC_1.6.2>, objp=0x7fffc40018e8) at /home/stienlet/ganesha/nfs-ganesha/src/include/nfsv41.h:8732
#12 0x00000000004419ed in xdr_nfree (proc=0x44bed5 <xdr_COMPOUND4args>, objp=0x7fffc40018e8) at /home/stienlet/ganesha/nfs-ganesha/src/libntirpc/ntirpc/rpc/xdr.h:638
#13 0x000000000044dc2f in nfs_rpc_process_request (reqdata=0x7fffc40011e0) at /home/stienlet/ganesha/nfs-ganesha/src/MainNFSD/nfs_worker_thread.c:1432
#14 0x000000000044df96 in nfs_rpc_valid_NFS (req=0x7fffc40011e0) at /home/stienlet/ganesha/nfs-ganesha/src/MainNFSD/nfs_worker_thread.c:1539
#15 0x0000000000441474 in nfs_rpc_decode_request (xprt=0x7fffe4000d00, xdrs=0x7fffc4000f10) at /home/stienlet/ganesha/nfs-ganesha/src/MainNFSD/nfs_rpc_dispatcher_thread.c:1341
#16 0x00007ffff758ce1d in svc_rqst_xprt_task () from /lib64/libntirpc.so.1.6
#17 0x00007ffff758d432 in svc_rqst_run_task () from /lib64/libntirpc.so.1.6
#18 0x00007ffff7595cc7 in work_pool_thread () from /lib64/libntirpc.so.1.6
#19 0x00007ffff79bb594 in ?? () from /lib64/libpthread.so.0
#20 0x00007ffff72a6fdf in clone () from /lib64/libc.so.6

-> mount command on the client (also fedora28):
sudo mount -t nfs -o vers=4,mountport=2049,port=2049 192.168.1.17:/home/NFS /home/stienlet/tests/mount_point 
=> this looks like some kind of NULL pointer dereferencing/free (p=0xe5 )

**Comment by JoelStienlet** [comment]
Problem solved: I uninstalled libntirpc packaged by fedora, and installed the version from ganesha's source. 
Sorry for the disturbance.
