### ISSUE TITLE
FSAL_RGW: unexpected crash down

### ISSUE THREAD

**Issue by taoCH** [nfs-ganesha/nfs-ganesha#333]
Hi, I'm using nfs-ganesha 2.6.2 and Ceph 12.2.5. I did a read test with fsal_rgw and I met unexpected crash down of nfs-ganesha, here is the bug trace:
```
#0  0x00007fdf4d7b659b in raise () from /lib64/libpthread.so.0
#1  0x00007fdf3d4afe06 in handle_fatal_signal(int) () from /lib64/librgw.so.2
#2  <signal handler called>
#3  0x00007fdf4ca3f277 in raise () from /lib64/libc.so.6
#4  0x00007fdf4ca40968 in abort () from /lib64/libc.so.6
#5  0x00007fdf4ca38096 in __assert_fail_base () from /lib64/libc.so.6
#6  0x00007fdf4ca38142 in __assert_fail () from /lib64/libc.so.6
#7  0x00007fdf3d177318 in void boost::intrusive::detail::destructor_impl<boost::intrusive::generic_hook<(boost::intrusive::algo_types)5, boost::intrusive::rbtree_node_traits<void*, false>, boost::intrusive::member_tag, (boost::intrusive::link_mode_type)1, (boost::intrusive::base_hook_type)0> >(boost::intrusive::generic_hook<(boost::intrusive::algo_types)5, boost::intrusive::rbtree_node_traits<void*, false>, boost::intrusive::member_tag, (boost::intrusive::link_mode_type)1, (boost::intrusive::base_hook_type)0>&, boost::intrusive::detail::link_dispatch<(boost::intrusive::link_mode_type)1>) [clone .isra.882] () from /lib64/librgw.so.2
#8  0x00007fdf3d17b02d in rgw::RGWFileHandle::~RGWFileHandle() () from /lib64/librgw.so.2
#9  0x00007fdf3d17b0a9 in rgw::RGWFileHandle::~RGWFileHandle() () from /lib64/librgw.so.2
#10 0x00007fdf3d177df2 in rgw_fh_rele () from /lib64/librgw.so.2
#11 0x00007fdf3d7d4416 in release () from /usr/lib64/ganesha/libfsalrgw.so
#12 0x00000000005346ff in mdcache_lru_clean ()
#13 0x000000000053880f in mdcache_lru_get ()
#14 0x0000000000546851 in mdcache_alloc_handle ()
#15 0x00000000005481d2 in mdcache_new_entry ()
#16 0x000000000053c63a in mdcache_alloc_and_check_handle ()
#17 0x000000000054a6cf in mdc_lookup_uncached ()
#18 0x000000000054a3ba in mdc_lookup ()
#19 0x0000000000542e80 in mdc_open2_by_name ()
#20 0x00000000005435ab in mdcache_open2 ()
#21 0x00000000004325a8 in open2_by_name ()
#22 0x0000000000434988 in fsal_open2 ()
#23 0x000000000048eee8 in nfs3_create ()
#24 0x000000000045ba62 in nfs_rpc_process_request ()
#25 0x000000000045c221 in nfs_rpc_valid_NFS ()
#26 0x00007fdf4d37e294 in svc_vc_decode () from /lib64/libntirpc.so.1.6
#27 0x000000000044f1cb in nfs_rpc_decode_request ()
#28 0x00007fdf4d37e1a5 in svc_vc_recv () from /lib64/libntirpc.so.1.6
#29 0x00007fdf4d37a995 in svc_rqst_xprt_task () from /lib64/libntirpc.so.1.6
#30 0x00007fdf4d37ae0f in svc_rqst_epoll_events () from /lib64/libntirpc.so.1.6
#31 0x00007fdf4d37b0b1 in svc_rqst_epoll_loop () from /lib64/libntirpc.so.1.6
#32 0x00007fdf4d37b164 in svc_rqst_run_task () from /lib64/libntirpc.so.1.6
#33 0x00007fdf4d38423f in work_pool_thread () from /lib64/libntirpc.so.1.6
#34 0x00007fdf4d7aee25 in start_thread () from /lib64/libpthread.so.0
#35 0x00007fdf4cb07bad in clone () from /lib64/libc.so.6
```

I wonder if this bug has been fix in 2.7 dev ?  or maybe in Ceph side

**Comment by taoCH** [comment]
Ok, It was a bug in ceph, which has been fixed by @mattbenjamin : https://github.com/ceph/ceph/commit/2e0f35c57791818eac49974c85dd4dc8ed592c06

👍 

Issue closed
