### ISSUE TITLE
Abort after read2 returns ERR_FSAL_DELAY

### ISSUE THREAD

**Issue by dirk1730** [nfs-ganesha/nfs-ganesha#401]
Ganesha 2.7.1
Custom FSAL

Scenario:
read2()
FSAL calls callback with error ERR_FSAL_DELAY
Result: `src/FSAL/Stackable_FSALs/FSAL_MDCACHE/mdcache_hash.h:394 :cih_remove_checked :RW LOCK :CRIT :Error 35, write locking 0x7effc34cc6e8 (&cp->lock)`

There is a loop in the code causing this error:
```C
else if (ret.major == ERR_FSAL_DELAY)  // (file: mdcache_file.c, function: mdc_read_cb, line: 548)
 mdcache_kill_entry()  // (file: mdcache_file.c, function: mdc_read_cb, line: 549)
  cih_remove_checked()  // (file: mdcache_helpers.c, function: _mdcache_kill_entry, line: 3269)
    PTHREAD_RWLOCK_wrlock(&cp->lock);  // (file: mdcache_hash.h, function: cih_remove_checked, line: 394)
    avltree_remove()  // (file: mdcache_hash.h, function: cih_remove_checked, line: 401)
    mdcache_lru_unref()  // (file: mdcache_hash.h, function: cih_remove_checked, line: 406)
     mdcache_lru_clean()  // (file: mdcache_lru.c, function: _mdcache_lru_unref, line: 1989)
      if (entry->sub_handle)  // (file: mdcache_lru.c, function: mdcache_lru_clean, line: 466)
       fsal_close()  // (file: mdcache_lru.c, function: mdcache_lru_clean, line: 565)
       entry->sub_handle->obj_ops->release()  // (file: mdcache_lru.c, function: mdcache_lru_clean, line: 573)
       fsal_release_attrs()  // (file: mdcache_lru.c, function: mdcache_lru_clean, line: 588)
       mdc_clean_entry()  // (file: mdcache_lru.c, function: mdcache_lru_clean, line: 591) (mdcache_helpers.c)
        cih_remove_checked()  // (file: mdcache_helpers.c, function: mdc_clean_entry, line: 264)
         PTHREAD_RWLOCK_wrlock(&cp->lock);  // (file: mdcache_hash.h, function: cih_remove_checked, line: 394)  (*** BOOM ***)
```

**Comment by dang** [comment]
This is a refcount bug somewhere.  The read path should have a ref on the object, so the refcount should not drop to 0, so it should not attempt to free it at this point.  Can you post the entire backtrace of this callpath?

**Comment by dirk1730** [comment]
Backtrace from gdb:

```gdb
#0  0x00007f2b64c3a269 in raise (sig=6) at ../sysdeps/unix/sysv/linux/pt-raise.c:35
#1  0x00000000004419c9 in crash_handler (signo=6, info=0x7f2b50ffc0f0, ctx=0x7f2b50ffbfc0) at /home/dirk/projects/src/foos/client/nfs-ganesha/src/MainNFSD/nfs_init.c:242
#2  <signal handler called>
#3  0x00007f2b6468c428 in __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:54
#4  0x00007f2b6468e02a in __GI_abort () at abort.c:89
#5  0x0000000000540202 in cih_remove_checked (entry=0x7f2b480bb100) at /home/dirk/projects/src/foos/client/nfs-ganesha/src/FSAL/Stackable_FSALs/FSAL_MDCACHE/mdcache_hash.h:394
#6  0x000000000054102f in mdc_clean_entry (entry=0x7f2b480bb100) at /home/dirk/projects/src/foos/client/nfs-ganesha/src/FSAL/Stackable_FSALs/FSAL_MDCACHE/mdcache_helpers.c:264
#7  0x000000000052e2de in mdcache_lru_clean (entry=0x7f2b480bb100) at /home/dirk/projects/src/foos/client/nfs-ganesha/src/FSAL/Stackable_FSALs/FSAL_MDCACHE/mdcache_lru.c:591
#8  0x0000000000533082 in _mdcache_lru_unref (entry=0x7f2b480bb100, flags=0, func=0x5a4b70 <__func__.23133> "cih_remove_checked", line=406) at /home/dirk/projects/src/foos/client/nfs-ganesha/src/FSAL/Stackable_FSALs/FSAL_MDCACHE/mdcache_lru.c:1989
#9  0x00000000005402a7 in cih_remove_checked (entry=0x7f2b480bb100) at /home/dirk/projects/src/foos/client/nfs-ganesha/src/FSAL/Stackable_FSALs/FSAL_MDCACHE/mdcache_hash.h:406
#10 0x000000000054c052 in _mdcache_kill_entry (entry=0x7f2b480bb100, file=0x5a2430 "/home/dirk/projects/src/foos/client/nfs-ganesha/src/FSAL/Stackable_FSALs/FSAL_MDCACHE/mdcache_file.c", line=549, function=0x5a2620 <__func__.20183> "mdc_read_cb") at /home/dirk/projects/src/foos/client/nfs-ganesha/src/FSAL/Stackable_FSALs/FSAL_MDCACHE/mdcache_helpers.c:3269
#11 0x000000000053d84b in mdc_read_cb (obj=0x7f2b48084160, ret=..., obj_data=0x7f2b50ffcaf0, caller_data=0x7f2b59c2ad20) at /home/dirk/projects/src/foos/client/nfs-ganesha/src/FSAL/Stackable_FSALs/FSAL_MDCACHE/mdcache_file.c:549
#12 0x00007f2b60a2d649 in (anonymous namespace)::foos_obj_handle_op_read2 (obj_hdl=0x7f2b48084160, bypass=true, done_cb=0x53d756 <mdc_read_cb>, read_arg=0x7f2b50ffcaf0, caller_arg=0x7f2b59c2ad20) at /home/dirk/projects/src/foos/client/nfs-ganesha/src/FSAL/FSAL_FOOS/foos_handle.cpp:1619
#13 0x000000000053d92e in mdcache_read2 (obj_hdl=0x7f2b480bb138, bypass=true, done_cb=0x494f30 <nfs3_read_cb>, read_arg=0x7f2b50ffcaf0, caller_arg=0x7f2b50ffcbb0) at /home/dirk/projects/src/foos/client/nfs-ganesha/src/FSAL/Stackable_FSALs/FSAL_MDCACHE/mdcache_file.c:584
#14 0x00000000004958a8 in nfs3_read (arg=0x7f2b59c7bf08, req=0x7f2b59c7b800, res=0x7f2b59cb3140) at /home/dirk/projects/src/foos/client/nfs-ganesha/src/Protocols/NFS/nfs3_read.c:311
#15 0x0000000000458cd6 in nfs_rpc_process_request (reqdata=0x7f2b59c7b800) at /home/dirk/projects/src/foos/client/nfs-ganesha/src/MainNFSD/nfs_worker_thread.c:1330
#16 0x00000000004594f5 in nfs_rpc_valid_NFS (req=0x7f2b59c7b800) at /home/dirk/projects/src/foos/client/nfs-ganesha/src/MainNFSD/nfs_worker_thread.c:1550
#17 0x00007f2b65c1966e in svc_vc_decode (req=0x7f2b59c7b800) at /home/dirk/projects/src/foos/client/nfs-ganesha/src/libntirpc/src/svc_vc.c:825
#18 0x000000000044ba51 in nfs_rpc_decode_request (xprt=0x7f2b62827000, xdrs=0x7f2b453c8700) at /home/dirk/projects/src/foos/client/nfs-ganesha/src/MainNFSD/nfs_rpc_dispatcher_thread.c:1353
#19 0x00007f2b65c1957f in svc_vc_recv (xprt=0x7f2b62827000) at /home/dirk/projects/src/foos/client/nfs-ganesha/src/libntirpc/src/svc_vc.c:798
#20 0x00007f2b65c15aa5 in svc_rqst_xprt_task (wpe=0x7f2b62827218) at /home/dirk/projects/src/foos/client/nfs-ganesha/src/libntirpc/src/svc_rqst.c:767
#21 0x00007f2b65c15f45 in svc_rqst_epoll_events (sr_rec=0x7f2b628ccb10, n_events=1) at /home/dirk/projects/src/foos/client/nfs-ganesha/src/libntirpc/src/svc_rqst.c:939
#22 0x00007f2b65c161ed in svc_rqst_epoll_loop (sr_rec=0x7f2b628ccb10) at /home/dirk/projects/src/foos/client/nfs-ganesha/src/libntirpc/src/svc_rqst.c:1012
#23 0x00007f2b65c162b7 in svc_rqst_run_task (wpe=0x7f2b628ccb10) at /home/dirk/projects/src/foos/client/nfs-ganesha/src/libntirpc/src/svc_rqst.c:1048
#24 0x00007f2b65c1f12a in work_pool_thread (arg=0x7f2b52826520) at /home/dirk/projects/src/foos/client/nfs-ganesha/src/libntirpc/src/work_pool.c:181
#25 0x00007f2b64c306ba in start_thread (arg=0x7f2b50ffe700) at pthread_create.c:333
#26 0x00007f2b6475e41d in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:109

#12: Our custom FSAL implementation for read2 calls mdc_read_cb with posix2fsal_status(EBUSY)
```

**Comment by dang** [comment]
Okay, this is an actual bug.  Fix is proposed here:
 https://review.gerrithub.io/c/ffilz/nfs-ganesha/+/445712 MDCACHE - Don't drop the sentinal ref with the lock held
I'll make sure this gets into 2.7.2

**Comment by dirk1730** [comment]
Thanks Daniel, I'll try this fix.
Dirk.

**Comment by dirk1730** [comment]
Seems to work fine, thanks.
