### ISSUE TITLE
Missing dbus service on access allow

### ISSUE THREAD

**Issue by sebix** [nfs-ganesha/nfs-ganesha#483]
Hi,

we are using kolla-ansible all-in-one with openstack stein and manila version 1.27.0 on Ubuntu 18.04.2 with centos as base distro

When allowing an access, e.g. with `manila access-allow cephnfsshare ip 10.0.0.1` the state of the access turns to error after applying. In the logs of manila `/var/lib/docker/volumes/kolla_logs/_data/manila/manila-share.log` we could find a stacktrace which I posted below. The main part is:

    Error org.freedesktop.DBus.Error.ServiceUnknown: The name org.ganesha.nfsd was not provided by any .service files

I found similar (probably equivalent) bug reports in various projects:
* https://github.com/nfs-ganesha/nfs-ganesha/issues/219
* https://github.com/gluster/storhaug/issues/14
* https://sourceforge.net/p/nfs-ganesha/mailman/message/32227132/

We guess that either the service is missing, vm cannot access the dbus of the host system or missing permissions. We are also not sure if this is a problem of ganesha or kolla. Any hints are appreciated.

Thanks

```
2019-09-26 19:25:58.965 24 ERROR manila.share.drivers.ganesha.manager [req-2be80d0e-360a-4d12-ac00-02e3e2809880 5712895dbb694c9e91f3aecc8a3b322d ccd96b7c59214c349190a6c87f9991b2 - - -] Error while executing management command on Ganesha node <no name>: dbus call exportmgr.AddExport.: ProcessExecutionError: Unexpected error while running command.
2019-09-26 19:26:03.879 24 ERROR oslo_messaging.rpc.server [req-2be80d0e-360a-4d12-ac00-02e3e2809880 5712895dbb694c9e91f3aecc8a3b322d ccd96b7c59214c349190a6c87f9991b2 - - -] Exception during message handling: GaneshaCommandFailure: Ganesha management command failed.
Command: sudo manila-rootwrap /etc/manila/rootwrap.conf dbus-send --print-reply --system --dest=org.ganesha.nfsd /org/ganesha/nfsd/ExportMgr org.ganesha.nfsd.exportmgr.AddExport string:/etc/ganesha/export.d/share-619dc160-b0ce-4a0c-a2d9-d54c819717a7.conf string:EXPORT(Export_Id=114)
Exit code: 1
Stdout: u''
Stderr: u'Error org.freedesktop.DBus.Error.ServiceUnknown: The name org.ganesha.nfsd was not provided by any .service files\n'
2019-09-26 19:26:03.879 24 ERROR oslo_messaging.rpc.server Traceback (most recent call last):
2019-09-26 19:26:03.879 24 ERROR oslo_messaging.rpc.server   File "/var/lib/kolla/venv/lib/python2.7/site-packages/oslo_messaging/rpc/server.py", line 166, in _process_incoming
2019-09-26 19:26:03.879 24 ERROR oslo_messaging.rpc.server     res = self.dispatcher.dispatch(message)
2019-09-26 19:26:03.879 24 ERROR oslo_messaging.rpc.server   File "/var/lib/kolla/venv/lib/python2.7/site-packages/oslo_messaging/rpc/dispatcher.py", line 265, in dispatch
2019-09-26 19:26:03.879 24 ERROR oslo_messaging.rpc.server     return self._do_dispatch(endpoint, method, ctxt, args)
2019-09-26 19:26:03.879 24 ERROR oslo_messaging.rpc.server   File "/var/lib/kolla/venv/lib/python2.7/site-packages/oslo_messaging/rpc/dispatcher.py", line 194, in _do_dispatch
2019-09-26 19:26:03.879 24 ERROR oslo_messaging.rpc.server     result = func(ctxt, **new_args)
2019-09-26 19:26:03.879 24 ERROR oslo_messaging.rpc.server   File "/var/lib/kolla/venv/lib/python2.7/site-packages/manila/share/manager.py", line 186, in wrapped
2019-09-26 19:26:03.879 24 ERROR oslo_messaging.rpc.server     return f(self, *args, **kwargs)
2019-09-26 19:26:03.879 24 ERROR oslo_messaging.rpc.server   File "/var/lib/kolla/venv/lib/python2.7/site-packages/manila/utils.py", line 568, in wrapper
2019-09-26 19:26:03.879 24 ERROR oslo_messaging.rpc.server     return func(self, *args, **kwargs)
2019-09-26 19:26:03.879 24 ERROR oslo_messaging.rpc.server   File "/var/lib/kolla/venv/lib/python2.7/site-packages/manila/share/manager.py", line 3536, in update_access
2019-09-26 19:26:03.879 24 ERROR oslo_messaging.rpc.server     share_server=share_server)
2019-09-26 19:26:03.879 24 ERROR oslo_messaging.rpc.server   File "/var/lib/kolla/venv/lib/python2.7/site-packages/manila/share/access.py", line 283, in update_access_rules
2019-09-26 19:26:03.879 24 ERROR oslo_messaging.rpc.server     share_server=share_server)
2019-09-26 19:26:03.879 24 ERROR oslo_messaging.rpc.server   File "/var/lib/kolla/venv/lib/python2.7/site-packages/manila/share/access.py", line 322, in _update_access_rules
2019-09-26 19:26:03.879 24 ERROR oslo_messaging.rpc.server     share_server)
2019-09-26 19:26:03.879 24 ERROR oslo_messaging.rpc.server   File "/var/lib/kolla/venv/lib/python2.7/site-packages/manila/share/access.py", line 390, in _update_rules_through_share_driver
2019-09-26 19:26:03.879 24 ERROR oslo_messaging.rpc.server     share_server=share_server
2019-09-26 19:26:03.879 24 ERROR oslo_messaging.rpc.server   File "/var/lib/kolla/venv/lib/python2.7/site-packages/manila/share/drivers/cephfs/driver.py", line 273, in update_access
2019-09-26 19:26:03.879 24 ERROR oslo_messaging.rpc.server     share_server=share_server)
2019-09-26 19:26:03.879 24 ERROR oslo_messaging.rpc.server   File "/var/lib/kolla/venv/lib/python2.7/site-packages/manila/share/drivers/ganesha/__init__.py", line 308, in update_access
2019-09-26 19:26:03.879 24 ERROR oslo_messaging.rpc.server     self.ganesha.add_export(share['name'], confdict)
2019-09-26 19:26:03.879 24 ERROR oslo_messaging.rpc.server   File "/var/lib/kolla/venv/lib/python2.7/site-packages/manila/share/drivers/ganesha/manager.py", line 491, in add_export
2019-09-26 19:26:03.879 24 ERROR oslo_messaging.rpc.server     cmd=e.cmd)
2019-09-26 19:26:03.879 24 ERROR oslo_messaging.rpc.server GaneshaCommandFailure: Ganesha management command failed.
2019-09-26 19:26:03.879 24 ERROR oslo_messaging.rpc.server Command: sudo manila-rootwrap /etc/manila/rootwrap.conf dbus-send --print-reply --system --dest=org.ganesha.nfsd /org/ganesha/nfsd/Export
Mgr org.ganesha.nfsd.exportmgr.AddExport string:/etc/ganesha/export.d/share-619dc160-b0ce-4a0c-a2d9-d54c819717a7.conf string:EXPORT(Export_Id=114)
2019-09-26 19:26:03.879 24 ERROR oslo_messaging.rpc.server Exit code: 1
2019-09-26 19:26:03.879 24 ERROR oslo_messaging.rpc.server Stdout: u''
2019-09-26 19:26:03.879 24 ERROR oslo_messaging.rpc.server Stderr: u'Error org.freedesktop.DBus.Error.ServiceUnknown: The name org.ganesha.nfsd was not provided by any .service files\n'
2019-09-26 19:26:03.879 24 ERROR oslo_messaging.rpc.server
```

**Comment by ffilz** [comment]
Others have mentioned issues with using DBUS in these kinds of environments. Maybe someone with more specific knowledge will chime in.

**Comment by dang** [comment]
Did you try the change mentioned in https://github.com/nfs-ganesha/nfs-ganesha/issues/219 and if so, does it work?

**Comment by sebix** [comment]
Hi,

With
```
<policy context="default">
```
we have the same behaviour.

**Comment by dang** [comment]
Does openstack even allow dbus pass-through?  Do you maybe have to configure it?  I have almost no experience with openstack, so I'm not sure how much help I can be with this.

**Comment by sebix** [comment]
The `/run` directory (where the dbus socket resides) of the host is rw-mounted in the docker container, so the docker container should have full access to the host's dbus daemon.

**Comment by dadegeshuaige** [comment]
if \<policy context="default"\> is not useful.
I guess you are not install 'dbus-devel' rpm before compile and then the flag use_dbus cann't 
open like "USE_DBUS = OFF".

# yum -y install dbus-devel
# recompile the source file and make sure "USE_DBUS = ON"
# config \<policy context="root"\> in /etc/dbus-1/system.d/org.ganesha.nfsd.conf
# systemctl restart messagebus
# systemctl restart nfs-ganesha
# good luck

**Comment by ffilz** [comment]
Is this still an issue?

**Comment by ffilz** [comment]
Note that as a question, this would have been a better subject for the support mailing list, support@lists.nfs-ganesha.org

**Comment by sebix** [comment]
> Is this still an issue?

We didn't further pursue this after being stuck with this for months.

**Comment by ffilz** [comment]
Closing as unresolved, no more interest.
