### ISSUE TITLE
FSAL Gluster - Segfault in setglustercreds

### ISSUE THREAD

**Issue by Jason-Hendry** [nfs-ganesha/nfs-ganesha#501]
I have nfs-ganesha exporting a 2 node/8 (4x2) brick GlusterFS using NFSv4

This segfault occurs intermittently but almost once a week. I cannot reproduce the segfault in a matching non-production cluster. A similar segfault, glfs_export is NULL, is reported here: https://bugzilla.redhat.com/show_bug.cgi?id=1747349 but marked verified in older versions. 

Name        : nfs-ganesha
Arch        : x86_64
Version     : 2.7.6
Release     : 1.el7

Name        : glusterfs
Arch        : x86_64
Version     : 6.5
Release     : 1.el7

```
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib64/libthread_db.so.1".
Core was generated by `/usr/bin/ganesha.nfsd -L /var/log/ganesha/ganesha.log -f /etc/ganesha/ganesha.c'.
Program terminated with signal 11, Segmentation fault.
#0  0x00007f64c6820933 in setglustercreds (glfs_export=glfs_export@entry=0xffffffffffffffe0, uid=uid@entry=0x7f6470719d88, gid=gid@entry=0x7f6470719d8c, ngrps=1, groups=0x7f647061cd00, file=file@entry=0x7f64c68231b8 "/builddir/build/BUILD/nfs-ganesha-2.7.6/src/FSAL/FSAL_GLUSTER/handle.c", line=line@entry=1180, 
    function=function@entry=0x7f64c6823900 <__func__.24150> "glusterfs_close_my_fd") at /usr/src/debug/nfs-ganesha-2.7.6/src/FSAL/FSAL_GLUSTER/gluster_internal.c:219
219                     if (*uid != glfs_export->saveduid)
Missing separate debuginfos, use: debuginfo-install bzip2-libs-1.0.6-13.el7.x86_64 dbus-libs-1.10.24-7.el7.x86_64 elfutils-libelf-0.170-4.el7.x86_64 elfutils-libs-0.170-4.el7.x86_64 glibc-2.17-222.el7.x86_64 glusterfs-6.4-1.el7.x86_64 glusterfs-api-6.4-1.el7.x86_64 glusterfs-client-xlators-6.4-1.el7.x86_64 glusterfs-libs-6.4-1.el7.x86_64 gssproxy-0.7.0-17.el7.x86_64 keyutils-libs-1.5.8-3.el7.x86_64 krb5-libs-1.15.1-18.el7.x86_64 libacl-2.2.51-14.el7.x86_64 libattr-2.4.46-13.el7.x86_64 libblkid-2.23.2-52.el7.x86_64 libcap-2.22-9.el7.x86_64 libcom_err-1.42.9-11.el7.x86_64 libgcc-4.8.5-28.el7_5.1.x86_64 libgcrypt-1.5.3-14.el7.x86_64 libgpg-error-1.12-3.el7.x86_64 libnfsidmap-0.25-19.el7.x86_64 libselinux-2.5-12.el7.x86_64 libuuid-2.23.2-52.el7.x86_64 lz4-1.7.5-2.el7.x86_64 openssl-libs-1.0.2k-12.el7.x86_64 pcre-8.32-17.el7.x86_64 sssd-client-1.16.0-19.el7.x86_64 systemd-libs-219-57.el7.x86_64 xz-libs-5.2.2-1.el7.x86_64 zlib-1.2.7-17.el7.x86_64
(gdb) bt
#0  0x00007f64c6820933 in setglustercreds (glfs_export=glfs_export@entry=0xffffffffffffffe0, uid=uid@entry=0x7f6470719d88, gid=gid@entry=0x7f6470719d8c, ngrps=1, groups=0x7f647061cd00, file=file@entry=0x7f64c68231b8 "/builddir/build/BUILD/nfs-ganesha-2.7.6/src/FSAL/FSAL_GLUSTER/handle.c", line=line@entry=1180, 
    function=function@entry=0x7f64c6823900 <__func__.24150> "glusterfs_close_my_fd") at /usr/src/debug/nfs-ganesha-2.7.6/src/FSAL/FSAL_GLUSTER/gluster_internal.c:219
#1  0x00007f64c681ae90 in glusterfs_close_my_fd (my_fd=my_fd@entry=0x7f6470719d40) at /usr/src/debug/nfs-ganesha-2.7.6/src/FSAL/FSAL_GLUSTER/handle.c:1177
#2  0x00007f64c681afc0 in glusterfs_close2 (obj_hdl=0x7f648029e6b8, state=0x7f6470719c60) at /usr/src/debug/nfs-ganesha-2.7.6/src/FSAL/FSAL_GLUSTER/handle.c:2857
#3  0x000055a3d83b14b7 in mdcache_close2 (obj_hdl=0x7f64802a3558, state=<optimized out>) at /usr/src/debug/nfs-ganesha-2.7.6/src/FSAL/Stackable_FSALs/FSAL_MDCACHE/mdcache_file.c:830
#4  0x000055a3d834da6d in _state_del_locked (state=0x7f6470719c60, func=func@entry=0x55a3d83ecab0 <__func__.21152> "state_nfs4_state_wipe", line=line@entry=656) at /usr/src/debug/nfs-ganesha-2.7.6/src/SAL/nfs4_state.c:499
#5  0x000055a3d834f1e8 in state_nfs4_state_wipe (ostate=0x7f64802a37c0) at /usr/src/debug/nfs-ganesha-2.7.6/src/SAL/nfs4_state.c:656
#6  0x000055a3d834636c in state_wipe_file (obj=0x7f64802a3558) at /usr/src/debug/nfs-ganesha-2.7.6/src/SAL/state_misc.c:1309
#7  0x000055a3d83a1a5f in _mdcache_lru_unref (entry=entry@entry=0x7f64802a3520, flags=flags@entry=0, func=func@entry=0x55a3d83fd0e3 <__func__.21016> "mdcache_put", line=line@entry=196) at /usr/src/debug/nfs-ganesha-2.7.6/src/FSAL/Stackable_FSALs/FSAL_MDCACHE/mdcache_lru.c:1972
#8  0x000055a3d83afbb5 in mdcache_put (entry=0x7f64802a3520) at /usr/src/debug/nfs-ganesha-2.7.6/src/FSAL/Stackable_FSALs/FSAL_MDCACHE/mdcache_lru.h:196
#9  mdc_write_cb (obj=<optimized out>, ret=..., obj_data=0x7f64a5c47d30, caller_data=0x7f64383113c0) at /usr/src/debug/nfs-ganesha-2.7.6/src/FSAL/Stackable_FSALs/FSAL_MDCACHE/mdcache_file.c:629
#10 0x00007f64c681f0d0 in glusterfs_write2 (obj_hdl=0x7f648029e6b8, bypass=<optimized out>, done_cb=0x55a3d83afac0 <mdc_write_cb>, write_arg=0x7f64a5c47d30, caller_arg=0x7f64383113c0) at /usr/src/debug/nfs-ganesha-2.7.6/src/FSAL/FSAL_GLUSTER/handle.c:2203
#11 0x000055a3d83b1234 in mdcache_write2 (obj_hdl=0x7f64802a3558, bypass=<optimized out>, done_cb=<optimized out>, write_arg=0x7f64a5c47d30, caller_arg=<optimized out>) at /usr/src/debug/nfs-ganesha-2.7.6/src/FSAL/Stackable_FSALs/FSAL_MDCACHE/mdcache_file.c:660
#12 0x000055a3d82fdf98 in nfs4_write (op=0x7f6438339da0, data=<optimized out>, resp=0x7f6438371df0, info=0x0, io=FSAL_IO_WRITE) at /usr/src/debug/nfs-ganesha-2.7.6/src/Protocols/NFS/nfs4_op_write.c:451
#13 0x000055a3d82e1853 in nfs4_Compound (arg=<optimized out>, req=<optimized out>, res=0x7f6438366d10) at /usr/src/debug/nfs-ganesha-2.7.6/src/Protocols/NFS/nfs4_Compound.c:942
#14 0x000055a3d82d4d2f in nfs_rpc_process_request (reqdata=0x7f643835e6b0) at /usr/src/debug/nfs-ganesha-2.7.6/src/MainNFSD/nfs_worker_thread.c:1328
#15 0x000055a3d82d41fa in nfs_rpc_decode_request (xprt=0x7f6498000c20, xdrs=0x7f6438348320) at /usr/src/debug/nfs-ganesha-2.7.6/src/MainNFSD/nfs_rpc_dispatcher_thread.c:1345
#16 0x00007f64cce1170d in svc_rqst_xprt_task () from /lib64/libntirpc.so.1.7
#17 0x00007f64cce11c4a in svc_rqst_run_task () from /lib64/libntirpc.so.1.7
#18 0x00007f64cce19d0b in work_pool_thread () from /lib64/libntirpc.so.1.7
#19 0x00007f64cb3c0e25 in start_thread () from /lib64/libpthread.so.0
#20 0x00007f64cacccbad in clone () from /lib64/libc.so.6
```

**Comment by soumyakoduri** [comment]
I think https://review.gerrithub.io/c/ffilz/nfs-ganesha/+/467372 is not backported to V2.7.6. Please try latest V2.9*

**Comment by dang** [comment]
There will also be a new 2.8.x soon after 3.0 comes out.

**Comment by ffilz** [comment]
Closed as resolved.
