### ISSUE TITLE
crash with "double free or corruption" in svc_sendreply called from nfs_rpc_valid_NFS

### ISSUE THREAD

**Issue by jimhuaang** [nfs-ganesha/nfs-ganesha#567]
hi, 
here is the related info for tracing the crash  

### env
```
~# uname -rio
4.4.0-116-generic x86_64 GNU/Linux

ganesha.nfsd -v
NFS-Ganesha Release = V2.6.3

 dpkg -l | grep tirpc
ii  libntirpc-dev                        1.6.3-ubuntu1~xenial1                      amd64        new transport-independent RPC library - development files
ii  libntirpc1:amd64                     1.6.3-ubuntu1~xenial1                      amd64        new transport-independent RPC library
ii  libntirpc1-dbg:amd64                 1.6.3-ubuntu1~xenial1                      amd64        new transport-independent RPC library
ii  libtirpc1:amd64                      0.2.5-1ubuntu0.1                           amd64        transport-independent RPC library
```

### ganesha config
```
NFS_CORE_PARAM {
    mount_path_pseudo = true;
    DRC_Disabled = true;
    Clustered = true;
}
EXPORT_DEFAULTS {
    Attr_Expiration_Time = 0;
}
NFSv4 {
    Lease_Lifetime=20;
    Grace_Period = 20;
}

EXPORT
{
    Export_Id = 1;
    Path = /test_nfs;
    Pseudo = /test_nfs;
   
    CLIENT {
        Clients = *;
        Squash = None;
        Access_type = RW;
    }
    FSAL {
       Name = AQFS;  // indoor developed fsal backend
    }
}
```

### gdb backtrace
```
(gdb) bt
#0  0x00007ff826f6b428 in __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:54
#1  0x00007ff826f6d02a in __GI_abort () at abort.c:89
#2  0x00007ff826fad7ea in __libc_message (do_abort=do_abort@entry=2, fmt=fmt@entry=0x7ff8270c6ed8 "*** Error in `%s': %s: 0x%s ***\n") at ../sysdeps/posix/libc_fatal.c:175
#3  0x00007ff826fb637a in malloc_printerr (ar_ptr=<optimized out>, ptr=<optimized out>, str=0x7ff8270c6ff0 "ree or corruption (out)", action=3) at malloc.c:5006
#4  _int_free (av=<optimized out>, p=<optimized out>, have_lock=0) at malloc.c:3867
#5  0x00007ff826fba53c in __GI___libc_free (mem=<optimized out>) at malloc.c:2968
#6  0x000055a0c4c04585 in gsh_free_size (p=0x7ff764003630, n=8192) at /home/builder/packages/ganesha/qfs-ganesha-2.0.0/src/include/abstract_mem.h:287
#7  0x00007ff82732779d in mem_free (n=<optimized out>, p=<optimized out>) at /home/builder/packages/ntirpc/ntirpc-1.0/ntirpc/rpc/types.h:215
#8  xdr_ioq_uv_release (uv=0x7ff7640008c0) at /home/builder/packages/ntirpc/ntirpc-1.0/src/xdr_ioq.c:202
#9  0x00007ff827327cf5 in xdr_ioq_release (ioqh=0x7ff7640035b8) at /home/builder/packages/ntirpc/ntirpc-1.0/src/xdr_ioq.c:703
#10 0x00007ff827327b3d in xdr_ioq_destroy (xioq=0x7ff7640034d0, qsize=344) at /home/builder/packages/ntirpc/ntirpc-1.0/src/xdr_ioq.c:717
#11 0x00007ff827328292 in svc_ioq_write (xprt=0x7ff78c000f20, xioq=xioq@entry=0x7ff7640034d0, ifph=0x7ff82753d260 <ioq_ifqh>) at /home/builder/packages/ntirpc/ntirpc-1.0/src/svc_ioq.c:219
#12 0x00007ff827328576 in svc_ioq_write_now (xprt=<optimized out>, xioq=xioq@entry=0x7ff7640034d0) at /home/builder/packages/ntirpc/ntirpc-1.0/src/svc_ioq.c:264
#13 0x00007ff827321d3d in svc_vc_reply (req=0x7ff764000dc0) at /home/builder/packages/ntirpc/ntirpc-1.0/src/svc_vc.c:884
#14 0x000055a0c4c1e1cf in nfs_rpc_process_request (reqdata=0x7ff764000dc0) at /home/builder/packages/ganesha/qfs-ganesha-2.0.0/src/MainNFSD/nfs_worker_thread.c:1386
#15 0x000055a0c4c1e7cf in nfs_rpc_valid_NFS (req=0x7ff764000dc0) at /home/builder/packages/ganesha/qfs-ganesha-2.0.0/src/MainNFSD/nfs_worker_thread.c:1554
#16 0x000055a0c4c11081 in nfs_rpc_decode_request (xprt=0x7ff78c000f20, xdrs=0x7ff764000ae0) at /home/builder/packages/ganesha/qfs-ganesha-2.0.0/src/MainNFSD/nfs_rpc_dispatcher_thread.c:1341
#17 0x00007ff82731f61d in svc_rqst_xprt_task (wpe=0x7ff78c001138) at /home/builder/packages/ntirpc/ntirpc-1.0/src/svc_rqst.c:751
#18 0x00007ff82731fbea in svc_rqst_epoll_events (n_events=<optimized out>, sr_rec=0x55a0c6205160) at /home/builder/packages/ntirpc/ntirpc-1.0/src/svc_rqst.c:923
#19 svc_rqst_epoll_loop (sr_rec=<optimized out>) at /home/builder/packages/ntirpc/ntirpc-1.0/src/svc_rqst.c:996
#20 svc_rqst_run_task (wpe=0x55a0c6205160) at /home/builder/packages/ntirpc/ntirpc-1.0/src/svc_rqst.c:1032
#21 0x00007ff827328807 in work_pool_thread (arg=0x7ff7840008c0) at /home/builder/packages/ntirpc/ntirpc-1.0/src/work_pool.c:176
#22 0x00007ff82774d6ba in start_thread (arg=0x7ff79b5e9700) at pthread_create.c:333
#23 0x00007ff82703d3dd in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:74
#24 0x0000000000000000 in ?? ()
(gdb) frame 8
#8  xdr_ioq_uv_release (uv=0x7ff7640008c0) at /home/builder/packages/ntirpc/ntirpc-1.0/src/xdr_ioq.c:202
202     in /home/builder/packages/ntirpc/ntirpc-1.0/src/xdr_ioq.c
(gdb) p *uv
$6 = {uvq = {q = {tqe_next = 0x0, tqe_prev = 0x7ff7640035b8}, qsize = 0, qflags = 0}, u = {uio_refer = 0x0, uio_release = 0x0, uio_p1 = 0x0, uio_p2 = 0x0, uio_u1 = 0x0, uio_u2 = 0x0, uio_count = 0, uio_flags = 2, uio_references = 0, 
    uio_vio = 0x7ff764000918}, v = {vio_base = 0x7ff764003630 "\251\241M\240", vio_head = 0x7ff764003630 "\251\241M\240", vio_tail = 0x7ff764003790 "", vio_wrap = 0x7ff764005630 ""}}
```

**Comment by mattbenjamin** [comment]
hi @jimhuaang ;have you tested with the most recent ganesha 2.8.x?

**Comment by jimhuaang** [comment]
hi @madhuthorat, I have not tested it yet. I guess probably ganesha 2.8.x will not meet this problem. I 
will try to have a test probably.

**Comment by jimhuaang** [comment]
Finally, found the crash is caused by our FSAL deployment issue, the wrong version get installed.

**Comment by dang** [comment]
Thanks for the followup.
