### ISSUE TITLE
Questions about NFS4 with FSAL_RGW

### ISSUE THREAD

**Issue by fantastic2085** [nfs-ganesha/nfs-ganesha#589]
ganesha.nfsd-99644[svc_286] nfs4_Errno_verbose :NFS4 :CRIT :Error I/O error in nfs4_write_cb converted to NFS4ERR_IO but was set non-retryable
What is the cause of the above?

**Comment by dang** [comment]
It means an underlying filesystem returned EIO.  This error (along with several others) translates to NFS4ERR_IO error, and this message is indicating that this translation has happened, and what the original error was.

**Comment by fantastic2085** [comment]
@dang 

**system**:CentOS Linux release 7.7.1908 (Core)
**ganesha**:NFS-Ganesha Release = V2.7.3
**ceph version**：ceph version 14.2.8 (2d095e947a02261ce61424021bb43bd3022d35cb) nautilus (stable)
**dd version**:8.22

**mount path**:
172.27.12.20:/test1 on /mnt/test1 type nfs4 (rw,nodev,noexec,relatime,**sync**,vers=4.1,rsize=1048576,wsize=1048576,namlen=255,**soft**,proto=tcp,timeo=600,retrans=2,sec=sys,clientaddr=172.27.12.20,local_lock=none,addr=172.27.12.20)

**ganesha conf**:
NFS_Core_Param
{      Nb_Worker = 2048;
       Dispatch_Max_Reqs = 10000;
       Dispatch_Max_Reqs_Xprt = 2048;
       RPC_Ioq_ThrdMax = 4096;
       MaxRPCSendBufferSize = 9437184;
       MaxRPCRecvBufferSize = 9437184;
       NFS_Protocols = 3,4;
       RPC_Max_Connections = 10000;
       Bind_Addr = 172.27.12.20;
}
RGW {
        ceph_conf = "/etc/ceph/ceph.conf";
        cluster = "ceph";
        name = "client.rgw.nccloudslave1";       
}
EXPORT
{       
        Export_id=20135;
        Path = "/test1";
        Pseudo = /test1;
        Access_Type = RW;
        Protocols = 3,4;
        Transports = TCP;
        SecType = sys,krb5,krb5i,krb5p;
        Squash = no_root_squash;
        FSAL {  
                Name = RGW;
                User_Id = "test-nfs";
                Access_Key_Id ="123456";
                Secret_Access_Key = "123456";
        }
}

**ganesha**:
/usr/bin/ganesha.nfsd -L /var/log/ganesha/ganesha.log -f /etc/ganesha/ganesha.conf -N **NIV_FULL_DEBUG**

**comand**: dd if=/dev/zero of=out_dd bs=1M count=8000

**ganesha log**:
04/06/2020 11:00:42 : epoch 5ed85894 : nccloudslave1 : ganesha.nfsd-18120[svc_74] nfs4_Compound :NFS4 :DEBUG :Request 2: opcode 38 is OP_WRITE
04/06/2020 11:00:42 : epoch 5ed85894 : nccloudslave1 : ganesha.nfsd-18120[svc_74] nfs4_Compound :NFS4 :M_DBG :NFS4: MID DEBUG: Check export perms export = 000001e0 req = 00000040
04/06/2020 11:00:42 : epoch 5ed85894 : nccloudslave1 : ganesha.nfsd-18120[svc_74] check_resp_room :NFS4 :F_DBG :Status of OP_WRITE in position 2 is ok so far, op response size = 20 total response size would be = 116 out of max 1049480/3428
04/06/2020 11:00:42 : epoch 5ed85894 : nccloudslave1 : ganesha.nfsd-18120[svc_74] nfs4_Is_Fh_Invalid :FH :F_DBG :NFS4 Handle (21:0x43004ea7100b1a438f0b60899864c41f3559564309)
04/06/2020 11:00:42 : epoch 5ed85894 : nccloudslave1 : ganesha.nfsd-18120[svc_74] nfs4_Is_Fh_Invalid :FH :F_DBG :NFS4 Handle 0x0 export id 20135
04/06/2020 11:00:42 : epoch 5ed85894 : nccloudslave1 : ganesha.nfsd-18120[svc_74] nfs4_Check_Stateid :STATE :F_DBG :Check WRITE stateid flags ALL_0 ALL_1 CURRENT
04/06/2020 11:00:42 : epoch 5ed85894 : nccloudslave1 : ganesha.nfsd-18120[svc_74] state_id_value_hash_func :STATE :F_DBG :val = 1
04/06/2020 11:00:42 : epoch 5ed85894 : nccloudslave1 : ganesha.nfsd-18120[svc_74] state_id_rbt_hash_func :STATE :F_DBG :rbt = 1591236755
04/06/2020 11:00:42 : epoch 5ed85894 : nccloudslave1 : ganesha.nfsd-18120[svc_74] hashtable_getlatch :RW LOCK :F_DBG :Got write lock on 0x32bd840 (&(ht->partitions[index].lock)) at /builddir/build/BUILD/nfs-ganesha-2.7.3/hashtable/hashtable.c:496
04/06/2020 11:00:42 : epoch 5ed85894 : nccloudslave1 : ganesha.nfsd-18120[svc_74] key_locate :HT CACHE :F_DBG :hash hit index 1 slot 5701
04/06/2020 11:00:42 : epoch 5ed85894 : nccloudslave1 : ganesha.nfsd-18120[svc_74] compare_state_id :STATE :F_DBG :{OTHER=0x010000009458d85e07000000 {{CLIENTID Epoch=0x5ed85894 Counter=0x00000001} StateIdCounter=0x00000007}} vs {OTHER=0x010000009458d85e07000000 {{CLIENTID Epoch=0x5ed85894 Counter=0x00000001} StateIdCounter=0x00000007}}
04/06/2020 11:00:42 : epoch 5ed85894 : nccloudslave1 : ganesha.nfsd-18120[svc_74] hashtable_getlatch :STATE :F_DBG :Get State ID Table returning Value=0x7fd37c0041e0 {STATE 0x7fd37c0041e0 OTHER=0x010000009458d85e07000000 {{CLIENTID Epoch=0x5ed85894 Counter=0x00000001} StateIdCounter=0x00000007} obj=0x7fd37c004248 type=SHARE seqid=1 owner={STATE_OPEN_OWNER_NFSV4 0x7fd3b8004820: clientid={0x7fd3bc001780 ClientID={Epoch=0x5ed85894 Counter=0x00000001} CONFIRMED Client={0x7fd3bc001690 name=(27:Linux NFSv4.1 nccloudslave1) refcount=1} t_delta=0 reservations=2 refcount=3} owner=(24:0x6f70656e2069643a000000e700000000000519e075a9cc4e) confirmed=1 seqid=0 refcount=1} refccount=1}
04/06/2020 11:00:42 : epoch 5ed85894 : nccloudslave1 : ganesha.nfsd-18120[svc_74] inc_state_t_ref :STATE :F_DBG :State 0x7fd37c0041e0 refcount now 2
04/06/2020 11:00:42 : epoch 5ed85894 : nccloudslave1 : ganesha.nfsd-18120[svc_74] hashtable_releaselatched :RW LOCK :F_DBG :Unlocked 0x32bd840 (&ht->partitions[latch->index].lock) at /builddir/build/BUILD/nfs-ganesha-2.7.3/hashtable/hashtable.c:562
04/06/2020 11:00:42 : epoch 5ed85894 : nccloudslave1 : ganesha.nfsd-18120[svc_74] get_state_obj_export_owner_refs :RW LOCK :F_DBG :Acquired mutex 0x7fd37c004210 (&state->state_mutex) at /builddir/build/BUILD/nfs-ganesha-2.7.3/SAL/nfs4_state.c:562
04/06/2020 11:00:42 : epoch 5ed85894 : nccloudslave1 : ganesha.nfsd-18120[svc_74] get_state_obj_export_owner_refs :STATE :F_DBG :state 0x7fd37c0041e0 state_obj 0x7fd37c004248 state_export 0x1265408 state_owner 0x7fd3b8004820
04/06/2020 11:00:42 : epoch 5ed85894 : nccloudslave1 : ganesha.nfsd-18120[svc_74] inc_state_owner_ref :STATE :F_DBG :Increment refcount now=2 {STATE_OPEN_OWNER_NFSV4 0x7fd3b8004820: clientid={0x7fd3bc001780 ClientID={Epoch=0x5ed85894 Counter=0x00000001} CONFIRMED Client={0x7fd3bc001690 name=(27:Linux NFSv4.1 nccloudslave1) refcount=1} t_delta=0 reservations=2 refcount=3} owner=(24:0x6f70656e2069643a000000e700000000000519e075a9cc4e) confirmed=1 seqid=0 refcount=1}
04/06/2020 11:00:42 : epoch 5ed85894 : nccloudslave1 : ganesha.nfsd-18120[svc_74] get_state_obj_export_owner_refs :RW LOCK :F_DBG :Released mutex 0x7fd37c004210 (&state->state_mutex) at /builddir/build/BUILD/nfs-ganesha-2.7.3/SAL/nfs4_state.c:593
04/06/2020 11:00:42 : epoch 5ed85894 : nccloudslave1 : ganesha.nfsd-18120[svc_74] nfs4_Check_Stateid :STATE :F_DBG :Check WRITE stateid found valid stateid OTHER=0x010000009458d85e07000000 {{CLIENTID Epoch=0x5ed85894 Counter=0x00000001} StateIdCounter=0x00000007} seqid=0 - 0x7fd37c0041e0
04/06/2020 11:00:42 : epoch 5ed85894 : nccloudslave1 : ganesha.nfsd-18120[svc_74] _mdcache_lru_unref :RW LOCK :F_DBG :Acquired mutex 0x7b8920 (&(qlane)->mtx) at /builddir/build/BUILD/nfs-ganesha-2.7.3/FSAL/Stackable_FSALs/FSAL_MDCACHE/mdcache_lru.c:1969
04/06/2020 11:00:42 : epoch 5ed85894 : nccloudslave1 : ganesha.nfsd-18120[svc_74] _mdcache_lru_unref :RW LOCK :F_DBG :Released mutex 0x7b8920 (&(qlane)->mtx) at /builddir/build/BUILD/nfs-ganesha-2.7.3/FSAL/Stackable_FSALs/FSAL_MDCACHE/mdcache_lru.c:1976
04/06/2020 11:00:42 : epoch 5ed85894 : nccloudslave1 : ganesha.nfsd-18120[svc_74] dec_state_owner_ref :STATE :F_DBG :Decrement refcount now=1 {STATE_OPEN_OWNER_NFSV4 0x7fd3b8004820: clientid={0x7fd3bc001780 ClientID={Epoch=0x5ed85894 Counter=0x00000001} CONFIRMED Client={0x7fd3bc001690 name=(27:Linux NFSv4.1 nccloudslave1) refcount=1} t_delta=0 reservations=2 refcount=3} owner=(24:0x6f70656e2069643a000000e700000000000519e075a9cc4e) confirmed=1 seqid=0 refcount=2}
04/06/2020 11:00:42 : epoch 5ed85894 : nccloudslave1 : ganesha.nfsd-18120[svc_74] inc_state_t_ref :STATE :F_DBG :State 0x7fd37c0041e0 refcount now 3
04/06/2020 11:00:42 : epoch 5ed85894 : nccloudslave1 : ganesha.nfsd-18120[svc_74] nfs4_write :NFS4 :F_DBG :offset = 6641246208  length = 434176  stable = 2
04/06/2020 11:00:42 : epoch 5ed85894 : nccloudslave1 : ganesha.nfsd-18120[svc_74] nfs4_write :NFS4 :F_DBG :Write offset=6641246208 count=434176 MaxOffSet=9223372036854775807
04/06/2020 11:00:42 : epoch 5ed85894 : nccloudslave1 : ganesha.nfsd-18120[svc_74] nfs4_write :NFS4 :F_DBG :offset = 6641246208 length = 434176
04/06/2020 11:00:42 : epoch 5ed85894 : nccloudslave1 : ganesha.nfsd-18120[svc_74] rgw_fsal_write2 :FSAL :F_DBG :rgw_fsal_write2 enter obj_hdl 0x7fd37c003b40 state 0x7fd37c0041e0
04/06/2020 11:00:44 : epoch 5ed85894 : **nccloudslave1 : ganesha.nfsd-18120[svc_74] nfs4_Errno_verbose :NFS4 :CRIT :Error I/O error in nfs4_write_cb converted to NFS4ERR_IO but was set non-retryable**
04/06/2020 11:00:44 : epoch 5ed85894 : nccloudslave1 : ganesha.nfsd-18120[svc_74] dec_nfs4_state_ref :STATE :F_DBG :Decrement refcount now=4 {STATE 0x7fd37c0041e0 OTHER=0x010000009458d85e07000000 {{CLIENTID Epoch=0x5ed85894 Counter=0x00000001} StateIdCounter=0x00000007} obj=0x7fd37c004248 type=SHARE seqid=1 owner={STATE_OPEN_OWNER_NFSV4 0x7fd3b8004820: clientid={0x7fd3bc001780 ClientID={Epoch=0x5ed85894 Counter=0x00000001} CONFIRMED Client={0x7fd3bc001690 name=(27:Linux NFSv4.1 nccloudslave1) refcount=1} t_delta=0 reservations=2 refcount=3} owner=(24:0x6f70656e2069643a000000e700000000000519e075a9cc4e) confirmed=1 seqid=0 refcount=1} refccount=5}
04/06/2020 11:00:44 : epoch 5ed85894 : nccloudslave1 : ganesha.nfsd-18120[svc_74] dec_nfs4_state_ref :STATE :F_DBG :Decrement refcount now=2 {STATE 0x7fd37c0041e0 OTHER=0x010000009458d85e07000000 {{CLIENTID Epoch=0x5ed85894 Counter=0x00000001} StateIdCounter=0x00000007} obj=0x7fd37c004248 type=SHARE seqid=1 owner={STATE_OPEN_OWNER_NFSV4 0x7fd3b8004820: clientid={0x7fd3bc001780 ClientID={Epoch=0x5ed85894 Counter=0x00000001} CONFIRMED Client={0x7fd3bc001690 name=(27:Linux NFSv4.1 nccloudslave1) refcount=1} t_delta=0 reservations=2 refcount=3} owner=(24:0x6f70656e2069643a000000e700000000000519e075a9cc4e) confirmed=1 seqid=0 refcount=1} refccount=3}
04/06/2020 11:00:44 : epoch 5ed85894 : nccloudslave1 : ganesha.nfsd-18120[svc_74] LogCompoundFH :FH :F_DBG :Current FH  File Handle V4: Len=21 43004ea7100b1a438f0b60899864c41f3559564309
04/06/2020 11:00:44 : epoch 5ed85894 : nccloudslave1 : ganesha.nfsd-18120[svc_74] LogCompoundFH :FH :F_DBG :Saved FH    File Handle V4: Len=0 <null>
04/06/2020 11:00:44 : epoch 5ed85894 : nccloudslave1 : ganesha.nfsd-18120[svc_74] nfs4_Compound :NFS4 :**DEBUG :Status of OP_WRITE in position 2** = NFS4ERR_IO, op response size is 4 total response size is 92
04/06/2020 11:00:44 : epoch 5ed85894 : nccloudslave1 : ganesha.nfsd-18120[svc_74] nfs4_Compound :SESSIONS :F_DBG :Save result in session replay cache 0x7fd3d0008870 sizeof nfs_res_t=264
04/06/2020 11:00:44 : epoch 5ed85894 : nccloudslave1 : ganesha.nfsd-18120[svc_74] nfs4_Compound :RW LOCK :F_DBG :Acquired mutex 0x7fd3bc001800 (&data.preserved_clientid->cid_mutex) at /builddir/build/BUILD/nfs-ganesha-2.7.3/Protocols/NFS/nfs4_Compound.c:1098
04/06/2020 11:00:44 : epoch 5ed85894 : nccloudslave1 : ganesha.nfsd-18120[svc_74] update_lease :CLIENT ID :F_DBG :Update Lease 0x7fd3bc001780 ClientID={Epoch=0x5ed85894 Counter=0x00000001} CONFIRMED Client={0x7fd3bc001690 name=(27:Linux NFSv4.1 nccloudslave1) refcount=1} t_delta=0 reservations=1 refcount=3
04/06/2020 11:00:44 : epoch 5ed85894 : nccloudslave1 : ganesha.nfsd-18120[svc_74] nfs4_Compound :RW LOCK :F_DBG :Released mutex 0x7fd3bc001800 (&data.preserved_clientid->cid_mutex) at /builddir/build/BUILD/nfs-ganesha-2.7.3/Protocols/NFS/nfs4_Compound.c:1102
04/06/2020 11:00:44 : epoch 5ed85894 : nccloudslave1 : ganesha.nfsd-18120[svc_74] nfs4_Compound :NFS4 :DEBUG :End status = NFS4ERR_IO lastindex = 2

however, if comamd is **dd if=/dev/urandom of=/mnt/test1/local_dd_8G_uradom_1 bs=900K count=9000**  no NFS4ERR_IO success rate100%!  why?

**Comment by dang** [comment]
The first issue is the version.  2.7.3 is very old.  At least upgrade to 2.7.6, if not 2.8.4, since there are many bug fixes in newer versions.

Next, speculation.

RGW can't overwrite in the middle of a file.  This is because S3 only allows writing entire files, so RGW limits writes to appends.  My guess is that the dd generated out-of-order writes, which triggered this error.  Your mount is "sync", which I would think should avoid this, however, so I'm not sure.

**Comment by fantastic2085** [comment]
@dang 
I find the issue:https://github.com/nfs-ganesha/nfs-ganesha/issues/390 says; when mount to use sync so I add sync

using comand: dd if=/dev/urandom of=/mnt/test1/local_dd_8G_uradom_1 bs=900K count=9000 oflag=append conv=notrunc  NFS4ERR_IO also happend

I'm very confused why?

**Comment by dang** [comment]
Like I said, 2.7.3 is very old.  Try something newer, many bugs have been fixed.

**Comment by livelace** [comment]
Caught the same problem. I use ganesha 3.3 and ceph rgw 15.2.4.
The initial case arised from a java app that couldn't write data into mounted bucket.
I preformed some tests with "dd" and the problem dissapeared with "sync" mount option.

```
10.0.102.8:/s3-bucket on /mnt/tmp type nfs4 (rw,relatime,sync,vers=4.2,rsize=1048576,wsize=1048576,namlen=255,hard,proto=tcp,timeo=600,retrans=2,sec=sys,clientaddr=10.0.102.2,local_lock=none,addr=10.0.102.8)
```

**Comment by livelace** [comment]
The story is continuing. 

If "dd" works:

```sh
for i in {1..300};do 
  dd if=/dev/urandom of=/mnt/tmp/fff bs=1M count=$i >/dev/null 2>&1
  if [ "$?" -ne 0 ];then 
    echo "$(date +%s): problem with: ${i}MB"
  fi
done
```

"python code" produces errors:

```python
with open("/mnt/tmp/test", "w") as f:
    f.write("a"*100000000)
```

```sh
zzz ~ # for i in {1..100};do python 1.py;done
Traceback (most recent call last):
  File "1.py", line 2, in <module>
    f.write("a"*100000000)
OSError: [Errno 5] Input/output error
Traceback (most recent call last):
  File "1.py", line 2, in <module>
    f.write("a"*100000000)
OSError: [Errno 5] Input/output error
Traceback (most recent call last):
  File "1.py", line 2, in <module>
    f.write("a"*100000000)
OSError: [Errno 5] Input/output error
Traceback (most recent call last):
  File "1.py", line 2, in <module>
    f.write("a"*100000000)
OSError: [Errno 5] Input/output error
```

**Comment by livelace** [comment]
@dang @ffilz Any thoughts, guys ?

**Comment by dang** [comment]
I'm not sure what python is doing; if the writes don't show up sequential at the server, they can't be treated as part of a single write, and so they will fail on RGW, because of the atomic-write-once properties of S3.  dd on a sync mount is obviously okay.  Is the python also on a sync mount?  (In general, you'll need sync mounts with FSAL_RGW).

**Comment by livelace** [comment]
yep, all tests done on "sync" mounts. 
does it mean there are **no guarantees** for apps which want to write into mounted buckets and they should use native s3 api instead ? 
if so, it's very unplesant, because there are too many apps for inspection/rewriting/adapting :(

**Comment by dang** [comment]
There's tentative work to extend librgw to allow more complicated read/write patterns planned, but it hasn't been started yet.  Since librgw is being used to implement a FUSE client, it will probably happen sooner rather than later.  But at the moment, RGW doesn't provide any way to re-write any portion of an object (since that's not allowed in S3), so there are limitations as to what's available for FSAL_RGW to accomplish.   If clients can support S3, that's always preferred at this point.

However, if full filesystem semantics are needed, you can use FSAL_CEPH, which uses CephFS as a backer.  This is a full POSIX filesystem, and provides all the necessary semantics.

**Comment by dang** [comment]
Sorry, I forgot to add that FSAL_RGW was originally written to provide backup/restore and migration for RGW/S3, so the limitations weren't a problem.

**Comment by livelace** [comment]
Ok, got it. Thanks for your answers. 
It would be fair to write about on the wiki page devoted FSAL_RGW. 
Right now it looks like a full functional access solution for Ceph RGW :(

**Comment by dang** [comment]
Just to be clear, this isn't a limitation of Ganesha, it's a limitation of Ceph RGW.  Ganesha provides full functional access to Ceph RGW, but RGW is not a full POSIX filesystem, so we cannot give full NFS access to it.   Right now, if you need a full POSIX filesystem on Ceph, you need to use CephFS.

You're right, though, it should be better documented.

**Comment by ffilz** [comment]
Looks like we should try and document RGW better.

**Comment by ffilz** [comment]
Daniel, could you look at documenting FSAL_RGW on the Wiki?

**Comment by ffilz** [comment]
Bump to keep live issues on first page

**Comment by ffilz** [comment]
There is some documentation linked from the Ceph project however we might still want a bit more words in the FSAL Support Wiki page.

**Comment by ffilz** [comment]
Another bump
