### ISSUE TITLE
Aborting gsh_malloc due to out of memory

### ISSUE THREAD

**Issue by dgengtek** [nfs-ganesha/nfs-ganesha#800]
Hi,

service is running in a lab on odroid-hc2 armbian. The SBC has 2GB of ram and during runtime 313Mi total is used while ganesha uses only ~35m RES, 351.9m VIRT. Maybe someone can help me to debug this issue further? 

After a short time the server gets killed by systemd with
```

Mar 07 21:17:46 odroidhc2-tretch systemd[1]: nfs-ganesha.service: Main process exited, code=killed, status=6/ABRT
Mar 07 21:17:46 odroidhc2-tretch systemd[1]: nfs-ganesha.service: Failed with result 'signal'.

```

Nothing else found in the journal or kernel logs. Running the service on the command line exits with code 134.

```

Distributor ID: Debian
Description:    Debian GNU/Linux 11 (bullseye)
Release:        11
Codename:       bullseye

ii  glusterfs-client               9.2-1                          armhf        clustered file-system (client package)
ii  glusterfs-common               9.2-1                          armhf        GlusterFS common libraries and translator modules
ii  glusterfs-server               9.2-1                          armhf        clustered file-system (server package)
ii  libglusterd0:armhf             9.2-1                          armhf        GlusterFS glusterd shared library
ii  libglusterfs0:armhf            9.2-1                          armhf        GlusterFS shared library
ii  libnfsidmap2:armhf             0.25-6                         armhf        NFS idmapping library
ii  nfs-common                     1:1.3.4-6                      armhf        NFS support files common to client and server
ii  nfs-ganesha                    3.4-1                          armhf        NFS server in User Space
ii  nfs-ganesha-gluster:armhf      3.4-1                          armhf        nfs-ganesha fsal gluster libraries
ii  nfs-ganesha-vfs:armhf          3.4-1                          armhf        nfs-ganesha fsal vfs libraries
```

```
# /etc/ganesha/ganesha.conf
FS_Core_Param {
    Protocols = "3","4";
    NFS_Port = 12049;
    MNT_Port = 20048;
    NLM_Port = 38468;
    Rquota_Port = 4501;
}
%include "/etc/ganesha/export.conf"
```
```
# /etc/ganesha/export.conf
EXPORT {
    Path = "/tmp";
    Pseudo = "/tmp";
    FSAL {
        Name = GLUSTER;
        volpath = "/tmp";
        volume = pool_hdd;
        hostname = "10.0.0.18";
    }
    Access_type = RW;
    Squash = all_squash;
    Anonymous_Uid = 40000;
    Anonymous_Gid = 40000;
    Disable_ACL = TRUE;
    SecType = "sys";
    Transports = "TCP";
    Export_Id = 2;
}
EXPORT {
    Path = "/homes";
    Pseudo = "/homes";
    FSAL {
        Name = "GLUSTER";
        volpath = "/homes";
        volume = "pool_hdd";
        hostname = "10.0.0.18";
    }
    Access_type = RW;
    Squash = No_root_squash;
    Disable_ACL = TRUE;
    SecType = "sys";
    Transports = "TCP";
    Export_Id = 3;
}

```
```
root@odroidhc2-tretch:~# ulimit -a
real-time non-blocking time  (microseconds, -R) unlimited
core file size              (blocks, -c) 0
data seg size               (kbytes, -d) unlimited
scheduling priority                 (-e) 0
file size                   (blocks, -f) unlimited
pending signals                     (-i) 14798
max locked memory           (kbytes, -l) 254781
max memory size             (kbytes, -m) unlimited
open files                          (-n) 1024
pipe size                (512 bytes, -p) 8
POSIX message queues         (bytes, -q) 819200
real-time priority                  (-r) 0
stack size                  (kbytes, -s) 8192
cpu time                   (seconds, -t) unlimited
max user processes                  (-u) 14798
virtual memory              (kbytes, -v) unlimited
file locks                          (-x) unlimited
```

Increasing max locked memory did not help.

Debug from command line https://pastebin.com/WsJP0vkn

**Comment by dgengtek** [comment]
Looked up exit code OPENHANDLE_ALLOCATE_BY_FD 139. Increasing open files (-n) limit seems to help.

**Comment by dgengtek** [comment]
Nevermind the service still fails with the same last message like in the debug logs `xdr_ioq_uv_create :MEM ALLOC :NULL :Aborting gsh_malloc due to out of memory`.

Any clues?

**Comment by dang** [comment]
It's possible that the machine is out of memory.  How much memory is available when Ganesha is running?  The kernel is quite bad at choosing what to kill due to lack of memory.

**Comment by dgengtek** [comment]
This is during runtime when nfs-ganesha is still running. Ganesha uses around ~30Mi after which it get signal killed.
```
root@odroidhc2-tretch:~# free -h
               total        used        free      shared  buff/cache   available
Mem:           1.9Gi       333Mi        54Mi       3.0Mi       1.6Gi       1.6Gi
Swap:             0B          0B          0B
```

How much memory is required to run ganesha?

**Comment by dgengtek** [comment]
I attached the valgrind logs. Maybe I am interpreting the output wrong but it seems like it is an issue with the arm allocator used by samba? Do I have a linking issue?

```

...
==3800==   Warning: whilst reading EXIDX: ExtabEntryExtract: bytecode can't be represented
--3800--   Reading EXIDX entries: 148 attempted, 38 successful
--3800-- Reading syms from /usr/lib/arm-linux-gnueabihf/libsmime3.so
--3800--    object doesn't have a symbol table
--3800-- Reading syms from /usr/lib/arm-linux-gnueabihf/libnss3.so
--3800--    object doesn't have a symbol table
--3800--   Reading EXIDX entries: 1 available
--3800--   Reading EXIDX entries: 0 attempted, 0 successful
--3800-- Reading syms from /usr/lib/arm-linux-gnueabihf/libnspr4.so
--3800--    object doesn't have a symbol table
--3800--   Reading EXIDX entries: 1 available
--3800--   Reading EXIDX entries: 0 attempted, 0 successful
--3800-- Reading syms from /usr/lib/arm-linux-gnueabihf/libudev.so.1.7.0
--3800--    object doesn't have a symbol table
--3800--   Reading EXIDX entries: 1 available
--3800--   Reading EXIDX entries: 0 attempted, 0 successful
--3800-- Reading syms from /usr/lib/arm-linux-gnueabihf/libibverbs.so.1.11.33.2
--3800--    object doesn't have a symbol table
--3800--   Reading EXIDX entries: 1 available
--3800--   Reading EXIDX entries: 0 attempted, 0 successful
--3800-- Reading syms from /usr/lib/arm-linux-gnueabihf/librdmacm.so.1.3.33.2
--3800--    object doesn't have a symbol table
--3800--   Reading EXIDX entries: 1 available
--3800--   Reading EXIDX entries: 0 attempted, 0 successful
--3800-- Reading syms from /usr/lib/arm-linux-gnueabihf/libz.so.1.2.11
--3800--    object doesn't have a symbol table
--3800--   Reading EXIDX entries: 1 available
--3800--   Reading EXIDX entries: 0 attempted, 0 successful
--3800-- Reading syms from /usr/lib/arm-linux-gnueabihf/libbz2.so.1.0.4
--3800--    object doesn't have a symbol table
--3800-- Reading syms from /usr/lib/arm-linux-gnueabihf/libnssutil3.so
--3800--    object doesn't have a symbol table
--3800-- Reading syms from /usr/lib/arm-linux-gnueabihf/libplc4.so
--3800--    object doesn't have a symbol table
--3800-- Reading syms from /usr/lib/arm-linux-gnueabihf/libplds4.so
--3800--    object doesn't have a symbol table
--3800-- Reading syms from /usr/lib/arm-linux-gnueabihf/libnl-route-3.so.200.26.0
--3800--    object doesn't have a symbol table
--3800-- Reading syms from /usr/lib/arm-linux-gnueabihf/libnl-3.so.200.26.0
--3800--    object doesn't have a symbol table
--3800--   Reading EXIDX entries: 1 available
--3800--   Reading EXIDX entries: 0 attempted, 0 successful
--3800-- REDIR: 0x5691b21 (libstdc++.so.6:operator new(unsigned int)) redirected to 0x4840da0 (operator new(unsigned int))
disInstr(thumb): unhandled instruction: 0xEC51 0x0F1E
==3800== valgrind: Unrecognised instruction at address 0xc4f3927.
==3800==    at 0xC4F3926: ??? (in /usr/lib/arm-linux-gnueabihf/libcrypto.so.1.1)
==3800== Your program just tried to execute an instruction that Valgrind
==3800== did not recognise.  There are two possible reasons for this.
==3800== 1. Your program has a bug and erroneously jumped to a non-code
==3800==    location.  If you are running Memcheck and you just saw a
==3800==    warning about a bad jump, it's probably your program's fault.
==3800== 2. The instruction is legitimate but Valgrind doesn't handle it,
==3800==    i.e. it's Valgrind's fault.  If you think this is the case or
==3800==    you are not sure, please let us know and we'll try to fix it.
==3800== Either way, Valgrind will now raise a SIGILL signal which will
==3800== probably kill your program.
--3800-- REDIR: 0x4a1f4e0 (libc.so.6:memmove) redirected to 0x48488c4 (memmove)
--3800-- REDIR: 0x56903e9 (libstdc++.so.6:operator delete(void*, unsigned int)) redirected to 0x48424ec (operator delete(void*, unsigned int))
--3800-- REDIR: 0x56903e5 (libstdc++.so.6:operator delete(void*)) redirected to 0x4842288 (operator delete(void*))
--3800-- REDIR: 0x4a1dff1 (libc.so.6:stpcpy) redirected to 0x4847ef8 (stpcpy)
--3800-- REDIR: 0x4a1eb85 (libc.so.6:strspn) redirected to 0x4849ecc (strspn)
--3800-- REDIR: 0x4a1e20d (libc.so.6:strcspn) redirected to 0x4849da4 (strcspn)
--3800-- REDIR: 0x4a1f93d (libc.so.6:strncasecmp) redirected to 0x484542c (strncasecmp)
--3800-- REDIR: 0x4a1e945 (libc.so.6:strpbrk) redirected to 0x4849d28 (strpbrk)
--3800-- Reading syms from /usr/lib/arm-linux-gnueabihf/libnss_files-2.31.so
--3800--   Considering /usr/lib/debug/.build-id/b9/c2a5c1497ccc93c7d20acfa11a39317fc6738e.debug ..
--3800--   .. build-id is valid
--3800-- REDIR: 0x4a1e001 (libc.so.6:strcpy) redirected to 0x4844a0c (strcpy)
--3800-- Reading syms from /usr/lib/arm-linux-gnueabihf/libnfsidmap/nsswitch.so
--3800--    object doesn't have a symbol table
--3800-- Reading syms from /usr/lib/arm-linux-gnueabihf/ganesha/libfsalgluster.so
--3800--    object doesn't have a symbol table
--3800-- Reading syms from /usr/lib/arm-linux-gnueabihf/libgfapi.so.0.0.0
--3800--    object doesn't have a symbol table
--3800-- Reading syms from /usr/lib/arm-linux-gnueabihf/libtirpc.so.3.0.0
--3800--    object doesn't have a symbol table
--3800-- Reading syms from /usr/lib/arm-linux-gnueabihf/libglusterfs.so.0.0.1
--3800--    object doesn't have a symbol table
--3800--   Reading EXIDX entries: 1 available
--3800--   Reading EXIDX entries: 0 attempted, 0 successful
--3800-- Reading syms from /usr/lib/arm-linux-gnueabihf/libgfrpc.so.0.0.1
--3800--    object doesn't have a symbol table
--3800-- Reading syms from /usr/lib/arm-linux-gnueabihf/libgfxdr.so.0.0.1
--3800--    object doesn't have a symbol table
--3800-- Reading syms from /usr/lib/arm-linux-gnueabihf/glusterfs/9.2/xlator/mount/api.so
--3800--    object doesn't have a symbol table
--3800-- Reading syms from /usr/lib/arm-linux-gnueabihf/glusterfs/9.2/rpc-transport/socket.so
--3800--    object doesn't have a symbol table
--3800-- Reading syms from /usr/lib/arm-linux-gnueabihf/libssl.so.1.1
--3800--    object doesn't have a symbol table
--3800-- REDIR: 0x4a1e6dd (libc.so.6:strnlen) redirected to 0x4844784 (strnlen)
--3800-- REDIR: 0x4a1f985 (libc.so.6:strcasecmp_l) redirected to 0x4845574 (strcasecmp_l)
==3800== Thread 13:
==3800== Invalid write of size 4
==3800==    at 0x4F1D9AA: sys_writev (in /usr/lib/arm-linux-gnueabihf/samba/libsys-rw.so.0)
==3800==  Address 0x14ccba68 is on thread 13's stack
==3800==  24 bytes below stack pointer
==3800== 
--3800-- Reading syms from /usr/lib/arm-linux-gnueabihf/glusterfs/9.2/xlator/protocol/client.so
--3800--    object doesn't have a symbol table
--3800-- Reading syms from /usr/lib/arm-linux-gnueabihf/glusterfs/9.2/xlator/cluster/afr.so
--3800--    object doesn't have a symbol table
--3800-- Reading syms from /usr/lib/arm-linux-gnueabihf/glusterfs/9.2/xlator/cluster/dht.so
--3800--    object doesn't have a symbol table
--3800--   Reading EXIDX entries: 1 available
--3800--   Reading EXIDX entries: 0 attempted, 0 successful
--3800-- Reading syms from /usr/lib/arm-linux-gnueabihf/glusterfs/9.2/xlator/features/utime.so
--3800--    object doesn't have a symbol table
--3800-- Reading syms from /usr/lib/arm-linux-gnueabihf/glusterfs/9.2/xlator/performance/write-behind.so
--3800--    object doesn't have a symbol table
--3800-- Reading syms from /usr/lib/arm-linux-gnueabihf/glusterfs/9.2/xlator/performance/open-behind.so
--3800--    object doesn't have a symbol table
--3800-- Reading syms from /usr/lib/arm-linux-gnueabihf/glusterfs/9.2/xlator/performance/quick-read.so
--3800--    object doesn't have a symbol table
--3800-- Reading syms from /usr/lib/arm-linux-gnueabihf/glusterfs/9.2/xlator/performance/md-cache.so
--3800--    object doesn't have a symbol table
--3800-- Reading syms from /usr/lib/arm-linux-gnueabihf/glusterfs/9.2/xlator/debug/io-stats.so
--3800--    object doesn't have a symbol table
--3800--   Reading EXIDX entries: 1 available
--3800--   Reading EXIDX entries: 0 attempted, 0 successful
--3800-- Reading syms from /usr/lib/arm-linux-gnueabihf/glusterfs/9.2/xlator/meta.so
--3800--    object doesn't have a symbol table
--3800-- REDIR: 0x4a1dc05 (libc.so.6:strcat) redirected to 0x48443d4 (strcat)
--3800-- Reading syms from /usr/lib/arm-linux-gnueabihf/libnss_dns-2.31.so
--3800--   Considering /usr/lib/debug/.build-id/f6/ec2b11be9a5727f98c1dafe34350416f236a71.debug ..
--3800--   .. build-id is valid
==3800== Warning: client switching stacks?  SP change: 0x11fe52b0 --> 0x151f1058
==3800==          to suppress, use: --max-stackframe=52477352 or greater
==3800== Warning: client switching stacks?  SP change: 0x151f1028 --> 0x11fe52b0
==3800==          to suppress, use: --max-stackframe=52477304 or greater
==3800== Warning: client switching stacks?  SP change: 0x127e62b0 --> 0x155f1058
==3800==          to suppress, use: --max-stackframe=48278952 or greater
==3800==          further instances of this message will not be shown.
--3800-- REDIR: 0x4a6a26d (libc.so.6:__strcpy_chk) redirected to 0x4849414 (__strcpy_chk)
==3800== 
==3800== Process terminating with default action of signal 6 (SIGABRT)
==3800==    at 0x49AB666: __libc_do_syscall (libc-do-syscall.S:47)
==3800==    by 0x49AA36F: __libc_signal_restore_set (internal-signals.h:86)
==3800==    by 0x49AA36F: raise (raise.c:48)
==3800==    by 0x49EACBF: ??? (sigrestorer.S:77)
--3800-- Archiving syms at 0xe1620c4-0xe166824 in /usr/lib/arm-linux-gnueabihf/libnss_files-2.31.so (have_dinfo 1)
--3800-- Scanning and archiving ExeContexts ...
--3800-- Scanned 7,108 ExeContexts, archived 43 ExeContexts
--3800-- Archiving syms at 0x14fddcec-0x14fdfab4 in /usr/lib/arm-linux-gnueabihf/libnss_dns-2.31.so (have_dinfo 1)
--3800-- Scanning and archiving ExeContexts ...
--3800-- Scanned 7,111 ExeContexts, archived 20 ExeContexts
==3800== 
==3800== HEAP SUMMARY:
==3800==     in use at exit: 29,197,750 bytes in 10,294 blocks
==3800==   total heap usage: 27,638 allocs, 17,344 frees, 38,912,036 bytes allocated
==3800== 
==3800== Searching for pointers to 10,294 not-freed blocks
==3800== Checked 286,857,460 bytes
==3800== 
==3800== Thread 1:
==3800== 146 bytes in 1 blocks are definitely lost in loss record 1 of 10
==3800==    at 0x484063C: malloc (in /usr/lib/arm-linux-gnueabihf/valgrind/vgpreload_memcheck-arm-linux.so)
==3800== 
==3800== 292 bytes in 20 blocks are possibly lost in loss record 2 of 10
==3800==    at 0x484053C: malloc (in /usr/lib/arm-linux-gnueabihf/valgrind/vgpreload_memcheck-arm-linux.so)
==3800== 
==3800== 644 bytes in 42 blocks are still reachable in loss record 3 of 10
==3800==    at 0x484053C: malloc (in /usr/lib/arm-linux-gnueabihf/valgrind/vgpreload_memcheck-arm-linux.so)
==3800== 
==3800== 1,336 bytes in 10 blocks are possibly lost in loss record 4 of 10
==3800==    at 0x484354C: realloc (in /usr/lib/arm-linux-gnueabihf/valgrind/vgpreload_memcheck-arm-linux.so)
==3800== 
==3800== 17,761 bytes in 54 blocks are still reachable in loss record 5 of 10
==3800==    at 0x484354C: realloc (in /usr/lib/arm-linux-gnueabihf/valgrind/vgpreload_memcheck-arm-linux.so)
==3800== 
==3800== 187,280 bytes in 574 blocks are possibly lost in loss record 6 of 10
==3800==    at 0x484063C: malloc (in /usr/lib/arm-linux-gnueabihf/valgrind/vgpreload_memcheck-arm-linux.so)
==3800== 
==3800== 355,155 bytes in 4,290 blocks are still reachable in loss record 7 of 10
==3800==    at 0x484063C: malloc (in /usr/lib/arm-linux-gnueabihf/valgrind/vgpreload_memcheck-arm-linux.so)
==3800== 
==3800== 881,707 bytes in 4,002 blocks are still reachable in loss record 8 of 10
==3800==    at 0x4840E2C: operator new(unsigned int) (in /usr/lib/arm-linux-gnueabihf/valgrind/vgpreload_memcheck-arm-linux.so)
==3800== 
==3800== 2,122,854 bytes in 274 blocks are possibly lost in loss record 9 of 10
==3800==    at 0x48432E4: calloc (in /usr/lib/arm-linux-gnueabihf/valgrind/vgpreload_memcheck-arm-linux.so)
==3800== 
==3800== 25,630,575 bytes in 1,027 blocks are still reachable in loss record 10 of 10
==3800==    at 0x48432E4: calloc (in /usr/lib/arm-linux-gnueabihf/valgrind/vgpreload_memcheck-arm-linux.so)
==3800== 
==3800== LEAK SUMMARY:
==3800==    definitely lost: 146 bytes in 1 blocks
==3800==    indirectly lost: 0 bytes in 0 blocks
==3800==      possibly lost: 2,311,762 bytes in 878 blocks
==3800==    still reachable: 26,885,842 bytes in 9,415 blocks
==3800==         suppressed: 0 bytes in 0 blocks
==3800== 
==3800== ERROR SUMMARY: 50 errors from 7 contexts (suppressed: 0 from 0)
==3800== 
==3800== 1 errors in context 1 of 7:
==3800== Invalid write of size 4
==3800==    at 0x529FF72: ??? (in /usr/lib/arm-linux-gnueabihf/libtalloc.so.2.3.1)
==3800==  Address 0xbddad5e0 is on thread 1's stack
==3800==  8 bytes below stack pointer
==3800== 
==3800== 
==3800== 44 errors in context 2 of 7:
==3800== Thread 13:
==3800== Invalid write of size 4
==3800==    at 0x4F1D9AA: sys_writev (in /usr/lib/arm-linux-gnueabihf/samba/libsys-rw.so.0)
==3800==  Address 0x14ccba68 is on thread 13's stack
==3800==  24 bytes below stack pointer
==3800== 
==3800== ERROR SUMMARY: 50 errors from 7 contexts (suppressed: 0 from 0)

```


[nfs-ganesha-valgrind.txt](https://github.com/nfs-ganesha/nfs-ganesha/files/8208195/nfs-ganesha-valgrind.txt)

**Comment by ffilz** [comment]
I'm out of practice with valgrind. Can you get full stacks for those apparent leaks?

**Comment by dgengtek** [comment]
Thank you for your replies. I installed the debug symbols for those errors in the summary.

```
...
==12217== ERROR SUMMARY: 52 errors from 7 contexts (suppressed: 0 from 0)
==12217==
==12217== 1 errors in context 1 of 7:
==12217== Invalid write of size 4
==12217==    at 0x5080F72: talloc_lib_init (talloc.c:397)
==12217==    by 0x400BF3F: call_init.part.0 (dl-init.c:72)
==12217==    by 0x400BFE1: call_init (dl-init.c:30)
==12217==    by 0x400BFE1: _dl_init (dl-init.c:119)
==12217==    by 0x4000AC3: ??? (in /usr/lib/arm-linux-gnueabihf/ld-2.31.so)
==12217==  Address 0xbde7e5e0 is on thread 1's stack
==12217==  8 bytes below stack pointer
==12217==
==12217==
==12217== 46 errors in context 2 of 7:
==12217== Thread 13:
==12217== Invalid write of size 4
==12217==    at 0x4EE09AA: sys_writev (sys_rw.c:121)
==12217==    by 0x14CCDB39: __socket_rwv (socket.c:725)
==12217==    by 0x14CCEBDB: UnknownInlinedFun (socket.c:830)
==12217==    by 0x14CCEBDB: UnknownInlinedFun (socket.c:1298)
==12217==    by 0x14CCEBDB: socket_submit_outgoing_msg (socket.c:3806)
==12217==    by 0xE6D6A5B: rpc_clnt_submit (rpc-clnt.c:1701)
==12217==    by 0xE5C433F: mgmt_submit_request.constprop.0 (glfs-mgmt.c:236)
==12217==    by 0xE5C8853: glfs_volfile_fetch.isra.0 (glfs-mgmt.c:800)
==12217==    by 0xE5B4503: mgmt_rpc_notify (glfs-mgmt.c:935)
==12217==    by 0xE6D5BFF: rpc_clnt_notify (rpc-clnt.c:964)
==12217==    by 0xE6D25AF: rpc_transport_notify (rpc-transport.c:520)
==12217==    by 0x14CD2891: socket_connect_finish (socket.c:2609)
==12217==    by 0x14CD3C97: UnknownInlinedFun (socket.c:2797)
==12217==    by 0x14CD3C97: UnknownInlinedFun (socket.c:2846)
==12217==    by 0x14CD3C97: UnknownInlinedFun (socket.c:2903)
==12217==    by 0x14CD3C97: socket_event_handler (socket.c:2854)
==12217==    by 0xE66EA61: UnknownInlinedFun (event-epoll.c:640)
==12217==    by 0xE66EA61: event_dispatch_epoll_worker (event-epoll.c:751)
==12217==    by 0x49A098D: start_thread (pthread_create.c:477)
==12217==    by 0x4A60BEB: ??? (clone.S:73)
==12217==  Address 0x14cc8a68 is on thread 13's stack
==12217==  24 bytes below stack pointer
==12217==
==12217== ERROR SUMMARY: 52 errors from 7 contexts (suppressed: 0 from 0)
```

**Comment by ffilz** [comment]
Are those actually Ganesha threads? Thread 13's stack at least shows that it's in Gluster code.

**Comment by dang** [comment]
How much memory Ganesha needs depends on the workload, but you have 1.3G available, so the box is not actually out of memory.  This means something else is causing the allocation failure.

The error appears to be in code from samba?  (/usr/lib/arm-linux-gnueabihf/samba/libsys-rw.so.0)  I'm not sure how this code is getting loaded?

ARM is not a well-used platform for Ganesha.  It's not impossible that there's a byte-order issue, although IBM does run with Power, so I'd hope those have all been caught.

**Comment by dgengtek** [comment]
> How much memory Ganesha needs depends on the workload, but you have 1.3G available, so the box is not actually out of memory. This means something else is causing the allocation failure.

It is just a homelab with no workload to mention. Nothing else runs on that device except some monitoring agents, gluster, samba and nfs-ganesha

> Are those actually Ganesha threads? Thread 13's stack at least shows that it's in Gluster code.

Ran it with gdb and the valgrind output probably is not relevant to the issue?

```
root@odroidhc2-tretch:~# gdb --args ganesha.nfsd -C -F  -f /etc/ganesha/ganesha.conf
GNU gdb (Debian 10.1-1.7) 10.1.90.20210103-git
Copyright (C) 2021 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
Type "show copying" and "show warranty" for details.
This GDB was configured as "arm-linux-gnueabihf".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<https://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
    <http://www.gnu.org/software/gdb/documentation/>.

For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from ganesha.nfsd...
Reading symbols from /usr/lib/debug/.build-id/51/808e592baf1aead467c5e7524276b1e4305aef.debug...
(gdb) thread apply all backtrace
(gdb) set print thread-events off
(gdb) r
Starting program: /usr/bin/ganesha.nfsd -C -F -f /etc/ganesha/ganesha.conf
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/arm-linux-gnueabihf/libthread_db.so.1".

Thread 20 "ganesha.nfsd" received signal SIGABRT, Aborted.
[Switching to Thread 0xa5afc920 (LWP 32198)]
__libc_do_syscall () at ../sysdeps/unix/sysv/linux/arm/libc-do-syscall.S:47
47      ../sysdeps/unix/sysv/linux/arm/libc-do-syscall.S: No such file or directory.
(gdb) bt
#0  __libc_do_syscall () at ../sysdeps/unix/sysv/linux/arm/libc-do-syscall.S:47
#1  0xb6d9bea0 in __libc_signal_restore_set (set=0xa5afbf9c) at ../sysdeps/unix/sysv/linux/internal-signals.h:86
#2  __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:48
#3  0xb6d8c7a2 in __GI_abort () at abort.c:79
#4  0xb6ecc376 in gsh_malloc__ (n=<optimized out>, file=0xa5afc920 "\001", line=0, function=0x1 <error: Cannot access memory at address 0x1>) at ./src/include/abstract_mem.h:82
#5  0xb6d520ce in xdr_ioq_uv_create (size=1347571544, uio_flags=uio_flags@entry=10) at ./src/xdr_ioq.c:73
#6  0xb6d4eb78 in svc_vc_recv (xprt=0xa4d02528) at ./src/svc_vc.c:768
#7  0xb6d4a624 in svc_rqst_xprt_task_recv (wpe=<optimized out>) at ./src/svc_rqst.c:1183
#8  0xb6d4b048 in svc_rqst_epoll_loop (wpe=0x1d757b8) at ./src/svc_rqst.c:1567
#9  0xb6d53aaa in work_pool_thread (arg=0xa6000768) at ./src/work_pool.c:184
#10 0xb6e7798e in start_thread (arg=0x73815d3d) at pthread_create.c:477
#11 0xb6e12bec in ?? () at ../sysdeps/unix/sysv/linux/arm/clone.S:73 from /lib/arm-linux-gnueabihf/libc.so.6
Backtrace stopped: previous frame identical to this frame (corrupt stack?)
(gdb)
```

I guess this is not an issue with nfs ganesha but probably with the device? Should I report this on armbians forum since this is not an issue with nfs ganesha?

**Comment by dang** [comment]
This may be a ganesha issue.  It looks like it's trying to allocate 1.3GB, which likely will fail.  My first thought was that it was a byte-order bug, but sx_fbtbc is byte-swapped properly in svc_vc_recv().   Maybe it's related to byte-swapping and the LAST_FRAG flag?  Or maybe it's a broken client that's sending a huge value?

**Comment by ffilz** [comment]
Hmm, I've been thinking about sx_fbtbc recently and a need to sanity check it before trying to allocate.

There has also been discussion about allocating a number of buffers instead of one big buffer, but that still doesn't resolve the situation where sx_fbtbc is an overly large value.

Also, if the issue is actually sx_fbtbc that's technically an ntirpc issue not a Ganesha issue.

I'm going to leave this one open for now because this is an actual case of an overly large sx_fbtbc value suggesting it isn't just an academic issue to be addressed. Adding some tags to add clarity.

**Comment by ffilz** [comment]
Bump
