### ISSUE TITLE
nfs-ganesha crashes at startup

### ISSUE THREAD

**Issue by guits** [nfs-ganesha/nfs-ganesha#848]
using devel build, nfs-ganesha crashes at startup.

stdout: [ganesha.log](https://github.com/nfs-ganesha/nfs-ganesha/files/9498409/stdout-ganesha.log)

with the following trace:

```
#0  raise (sig=6) at ../sysdeps/unix/sysv/linux/raise.c:50
#1  <signal handler called>
#2  __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:50
#3  0x00007efe53bc3ea5 in __GI_abort () at abort.c:79
#4  0x00007efe53c33097 in __libc_message (action=action@entry=do_abort, fmt=fmt@entry=0x7efe53d2c1f0 "%s\n") at ../sysdeps/posix/libc_fatal.c:181
#5  0x00007efe53c3a4ec in malloc_printerr (str=str@entry=0x7efe53d2a359 "free(): invalid pointer") at malloc.c:5375
#6  0x00007efe53c3bdec in _int_free (av=<optimized out>, p=<optimized out>, have_lock=<optimized out>) at malloc.c:4186
#7  0x00007efe4a463471 in arrow::util::StringBuilder<char const (&) [31]> () at /opt/rh/gcc-toolset-11/root/usr/include/c++/11/ostream:611
#8  arrow::Status::FromArgs<char const (&) [31]> (code=arrow::StatusCode::KeyError) at /usr/src/debug/ceph-17.0.0-14815.g9c828b72.el8.x86_64/src/arrow/cpp/src/arrow/status.h:161
#9  arrow::Status::KeyError<char const (&) [31]> () at /usr/src/debug/ceph-17.0.0-14815.g9c828b72.el8.x86_64/src/arrow/cpp/src/arrow/status.h:180
#10 arrow::internal::GetEnvVar[abi:cxx11](char const*) (name=name@entry=0x7efe4a5ecaf0 <arrow::(anonymous namespace)::kDefaultBackendEnvVar> "ARROW_DEFAULT_MEMORY_POOL")
    at /usr/src/debug/ceph-17.0.0-14815.g9c828b72.el8.x86_64/src/arrow/cpp/src/arrow/util/io_util.cc:1311
#11 0x00007efe4a33462d in operator() (__closure=<optimized out>) at /usr/src/debug/ceph-17.0.0-14815.g9c828b72.el8.x86_64/src/arrow/cpp/src/arrow/memory_pool.cc:155
#12 arrow::(anonymous namespace)::UserSelectedBackend () at /usr/src/debug/ceph-17.0.0-14815.g9c828b72.el8.x86_64/src/arrow/cpp/src/arrow/memory_pool.cc:172
#13 arrow::(anonymous namespace)::DefaultBackend () at /usr/src/debug/ceph-17.0.0-14815.g9c828b72.el8.x86_64/src/arrow/cpp/src/arrow/memory_pool.cc:178
#14 0x00007efe4a3353c0 in arrow::default_memory_pool () at /usr/src/debug/ceph-17.0.0-14815.g9c828b72.el8.x86_64/src/arrow/cpp/src/arrow/memory_pool.cc:539
#15 0x00007efe498372aa in arrow::io::IOContext::IOContext (this=0x7efe4a8ed820 <arrow::io::g_default_io_context>) at /opt/rh/gcc-toolset-11/root/usr/include/c++/11/bits/shared_ptr_base.h:1092
#16 __static_initialization_and_destruction_0 (__priority=65535, __initialize_p=1) at /usr/src/debug/ceph-17.0.0-14815.g9c828b72.el8.x86_64/src/arrow/cpp/src/arrow/io/interfaces.cc:52
#17 _GLOBAL__sub_I_interfaces.cc(void) () at /usr/src/debug/ceph-17.0.0-14815.g9c828b72.el8.x86_64/src/arrow/cpp/src/arrow/io/interfaces.cc:469
#18 0x00007efe5641305a in call_init (l=<optimized out>, argc=argc@entry=9, argv=argv@entry=0x7ffd8b7d25c8, env=env@entry=0x7ffd8b7d2618) at dl-init.c:72
#19 0x00007efe5641315a in call_init (env=0x7ffd8b7d2618, argv=0x7ffd8b7d25c8, argc=9, l=<optimized out>) at dl-init.c:30
#20 _dl_init (main_map=0x209b440, argc=9, argv=0x7ffd8b7d25c8, env=0x7ffd8b7d2618) at dl-init.c:119
#21 0x00007efe53d0bbac in __GI__dl_catch_exception (exception=exception@entry=0x0, operate=operate@entry=0x7efe5641a660 <call_dl_init>, args=args@entry=0x7ffd8b7d19b0) at dl-error-skeleton.c:182
#22 0x00007efe5641a89e in dl_open_worker (a=0x7ffd8b7d1b50) at dl-open.c:794
#23 dl_open_worker (a=a@entry=0x7ffd8b7d1b50) at dl-open.c:757
#24 0x00007efe53d0bb54 in __GI__dl_catch_exception (exception=exception@entry=0x7ffd8b7d1b30, operate=operate@entry=0x7efe5641a800 <dl_open_worker>, args=args@entry=0x7ffd8b7d1b50)
    at dl-error-skeleton.c:208
#25 0x00007efe5641aa81 in _dl_open (file=0x7ffd8b7d1e00 "/usr/lib64/ganesha/libfsalrgw.so", mode=-2147483638, caller_dlopen=0x7efe56040741 <load_fsal+353>, nsid=<optimized out>, argc=9,
    argv=<optimized out>, env=0x7ffd8b7d2618) at dl-open.c:875
#26 0x00007efe54f04f8a in dlopen_doit (a=a@entry=0x7ffd8b7d1dc0) at dlopen.c:66
#27 0x00007efe53d0bb54 in __GI__dl_catch_exception (exception=exception@entry=0x7ffd8b7d1d20, operate=<optimized out>, args=<optimized out>) at dl-error-skeleton.c:208
#28 0x00007efe53d0bc13 in __GI__dl_catch_error (objname=0x7ffd8b7d1d78, errstring=0x7ffd8b7d1d80, mallocedp=0x7ffd8b7d1d77, operate=<optimized out>, args=<optimized out>) at dl-error-skeleton.c:227
#29 0x00007efe54f0552e in _dlerror_run (operate=operate@entry=0x7efe54f04f30 <dlopen_doit>, args=args@entry=0x7ffd8b7d1dc0) at dlerror.c:142
#30 0x00007efe54f0502a in __dlopen (file=file@entry=0x7ffd8b7d1e00 "/usr/lib64/ganesha/libfsalrgw.so", mode=mode@entry=10) at dlopen.c:87
#31 0x00007efe56040741 in load_fsal (name=name@entry=0x20c9a50 "RGW", fsal_hdl_p=fsal_hdl_p@entry=0x7ffd8b7d1f08) at /usr/src/debug/nfs-ganesha-4.0-.8.el8.x86_64/FSAL/fsal_manager.c:228
#32 0x00007efe56041969 in fsal_load_init (node=node@entry=0x210b1f0, name=0x20c9a50 "RGW", fsal_hdl=fsal_hdl@entry=0x7ffd8b7d1f08, err_type=err_type@entry=0x7ffd8b7d23d0)
    at /usr/src/debug/nfs-ganesha-4.0-.8.el8.x86_64/FSAL/fsal_manager.c:541
#33 0x00007efe560c5a10 in fsal_cfg_commit (node=0x210b1f0, link_mem=0x20c9950, self_struct=0x21098e0, err_type=0x7ffd8b7d23d0) at /usr/src/debug/nfs-ganesha-4.0-.8.el8.x86_64/support/exports.c:758
#34 0x00007efe5607e7ac in proc_block (err_type=<optimized out>, link_mem=<optimized out>, item=<optimized out>, node=<optimized out>)
    at /usr/src/debug/nfs-ganesha-4.0-.8.el8.x86_64/config_parsing/config_parsing.c:1417
#35 proc_block (node=<optimized out>, item=<optimized out>, link_mem=<optimized out>, err_type=<optimized out>) at /usr/src/debug/nfs-ganesha-4.0-.8.el8.x86_64/config_parsing/config_parsing.c:1350
#36 0x00007efe5607e0c9 in do_block_load (err_type=<optimized out>, param_struct=<optimized out>, relax=<optimized out>, params=<optimized out>, blk=<optimized out>)
    at /usr/src/debug/nfs-ganesha-4.0-.8.el8.x86_64/config_parsing/config_parsing.c:1249
#37 proc_block (err_type=<optimized out>, link_mem=<optimized out>, item=<optimized out>, node=<optimized out>) at /usr/src/debug/nfs-ganesha-4.0-.8.el8.x86_64/config_parsing/config_parsing.c:1398
#38 proc_block (node=<optimized out>, item=<optimized out>, link_mem=<optimized out>, err_type=<optimized out>) at /usr/src/debug/nfs-ganesha-4.0-.8.el8.x86_64/config_parsing/config_parsing.c:1350
#39 0x00007efe5607f13a in load_config_from_parse (config=config@entry=0x20cbb30, conf_blk=conf_blk@entry=0x7efe563f0f60 <export_param>, param=param@entry=0x0, unique=unique@entry=false,
    err_type=err_type@entry=0x7ffd8b7d23d0) at /usr/src/debug/nfs-ganesha-4.0-.8.el8.x86_64/config_parsing/config_parsing.c:2014
#40 0x00007efe560c6116 in ReadExports (in_config=0x20cbb30, err_type=err_type@entry=0x7ffd8b7d23d0) at /usr/src/debug/nfs-ganesha-4.0-.8.el8.x86_64/support/exports.c:2239
41 0x000000000040211e in main (argc=<optimized out>, argv=<optimized out>) at /usr/src/debug/nfs-ganesha-4.0-.8.el8.x86_64/MainNFSD/nfs_main.c:507
```

ganesha version:
```
# ganesha.nfsd -v
NFS-Ganesha Release = V4.0.8
```

from devel repositories
```
[nfs-ganesha]
name=nfs-ganesha packages for $basearch
baseurl=https://4.chacra.ceph.com/r/nfs-ganesha/next/98fc2a9bbbc01a91a0b14626b9d8eae679d46bf1/centos/8/flavors/ceph_main/$basearch
enabled=1
gpgcheck=0
type=rpm-md

[nfs-ganesha-noarch]
name=nfs-ganesha noarch packages
baseurl=https://4.chacra.ceph.com/r/nfs-ganesha/next/98fc2a9bbbc01a91a0b14626b9d8eae679d46bf1/centos/8/flavors/ceph_main/noarch
enabled=1
gpgcheck=0
type=rpm-md

[nfs-ganesha-source]
name=nfs-ganesha source packages
baseurl=https://4.chacra.ceph.com/r/nfs-ganesha/next/98fc2a9bbbc01a91a0b14626b9d8eae679d46bf1/centos/8/flavors/ceph_main/SRPMS
enabled=1
gpgcheck=0
type=rpm-md
```

ganesha.conf:

```
[root@nfs0 ~]# cat /etc/ganesha/ganesha.conf
NFS_Core_Param
{

}
EXPORT
{
        Export_id=20134;

        Path = "/";

        Pseudo = /cephobject;

        Access_Type = RW;

        Protocols = 3,4;

        Transports = TCP;

        SecType = sys,krb5,krb5i,krb5p;

        Squash = Root_Squash;

        FSAL {
                Name = RGW;
                User_Id = "cephnfs";
                Access_Key_Id ="EL2AXHQYAL4R33T8EWAK";
                Secret_Access_Key = "bbNwlO8nLz70kSgejKdPtHZA29p162qk9I3Y8PPs";
        }



}
RGW {
        ceph_conf = "/etc/ceph/ceph.conf";
        cluster = "ceph";
        name = "client.rgw.nfs0";

}

LOG {
        Facility {
                name = FILE;
                destination = "/var/log/ganesha/ganesha.log";
                enable = active;
        }


}
CACHEINODE {
        Entries_HWMark = 100000;
}
```

```
[root@nfs0 ~]# ceph --version
ceph version 17.0.0-14815-g9c828b72 (9c828b72adb91af620643d335a9ff9127e724461) quincy (dev)
[root@nfs0 ~]# cat /etc/redhat-release
CentOS Stream release 8
[root@nfs0 ~]#
```

**Comment by jtlayton** [comment]
Looks like it's probably some sort of malloc arena corruption or something. The crash happened down in libc. It might be worthwhile to reproduce this under valgrind or build with ASAN and reproduce it that way.

**Comment by dang** [comment]
Also, make sure that both ceph and ganesha are built with the same allocator.  Both support libc, jemalloc, and tcmalloc, and you cannot mix them.

**Comment by ffilz** [comment]
Good point, please check that.

**Comment by guits** [comment]
in that case, https://github.com/ceph/ceph/pull/47628 might be related

**Comment by guits** [comment]
@dang @ffilz @jtlayton 
do you think https://github.com/ceph/ceph-build/pull/2069 would fix this?

**Comment by dang** [comment]
Probably, assuming the associated .deb and .spec files for ceph use TCMALLOC

**Comment by ffilz** [comment]
Looks like maybe there's a resolution. Closing.

**Comment by guits** [comment]
yeh @ffilz it was fixed by @dsavineau 

thanks everyone!
