### ISSUE TITLE
Hitting Ganesha core in _dec_session_ref 

### ISSUE THREAD

**Issue by sagsango** [nfs-ganesha/nfs-ganesha#884]
We Have seen this core dump twice on our lab environment, and not sure about the root cause

Back-Trace
```
(gdb) bt
#0 0x00007f2571e9f4fb in raise () from /lib64/libpthread.so.0
#1 0x00007f25737ab337 in crash_handler (signo=6, info=0x7f254e2c6970, ctx=0x7f254e2c6840) at /usr/src/debug/nfs-ganesha-4.0.2/MainNFSD/nfs_init.c:256
#2 \<signal handler called \>
#3 0x00007f25716d6387 in raise () from /lib64/libc.so.6
#4 0x00007f25716d7a78 in abort () from /lib64/libc.so.6
#5 0x00007f2573814227 in _dec_session_ref (session=0x7f254a412e00, func=0x7f2573922c70 <__func__.22740> "nfs4_op_destroy_session", line=97)
  at /usr/src/debug/nfs-ganesha-4.0.2/SAL/nfs41_session_id.c:263
#6 0x00007f257386714b in nfs4_op_destroy_session (op=0x7f2556c380a0, data=0x7f255302c800, resp=0x7f2556c38000)
  at /usr/src/debug/nfs-ganesha-4.0.2/Protocols/NFS/nfs4_op_destroy_session.c:97
#7 0x00007f257385fa43 in process_one_op (data=0x7f255302c800, status=0x7f254e2c787c) at /usr/src/debug/nfs-ganesha-4.0.2/Protocols/NFS/nfs4_Compound.c:924
#8 0x00007f2573860acb in nfs4_Compound (arg=0x7f219c59d880, req=0x7f219c59d000, res=0x7f254a591100)
  at /usr/src/debug/nfs-ganesha-4.0.2/Protocols/NFS/nfs4_Compound.c:1339
#9 0x00007f25737a5f80 in nfs_rpc_process_request (reqdata=0x7f219c59d000, retry=false)
  at /usr/src/debug/nfs-ganesha-4.0.2/MainNFSD/nfs_worker_thread.c:2055
#10 0x00007f25737a65f9 in nfs_rpc_valid_NFS (req=0x7f219c59d000) at /usr/src/debug/nfs-ganesha-4.0.2/MainNFSD/nfs_worker_thread.c:2293
#11 0x00007f2573b7ead6 in svc_vc_decode (req=0x7f219c59d000) at /usr/src/debug/nfs-ganesha-4.0.2/libntirpc/src/svc_vc.c:1126
#12 0x00007f2573b79c59 in svc_request (xprt=0x7f2558813000, xdrs=0x7f24e63bbe40) at /usr/src/debug/nfs-ganesha-4.0.2/libntirpc/src/svc_rqst.c:1229
#13 0x00007f2573b7e9db in svc_vc_recv (xprt=0x7f2558813000) at /usr/src/debug/nfs-ganesha-4.0.2/libntirpc/src/svc_vc.c:1099
#14 0x00007f2573b79bbd in svc_rqst_xprt_task_recv (wpe=0x7f25588132f0) at /usr/src/debug/nfs-ganesha-4.0.2/libntirpc/src/svc_rqst.c:1209
#15 0x00007f2573b7a840 in svc_rqst_epoll_loop (wpe=0x7f256e91df18) at /usr/src/debug/nfs-ganesha-4.0.2/libntirpc/src/svc_rqst.c:1608
#16 0x00007f2573b87cda in work_pool_thread (arg=0x7f255ec32da0) at /usr/src/debug/nfs-ganesha-4.0.2/libntirpc/src/work_pool.c:190
#17 0x00007f2571e97ea5 in start_thread () from /lib64/libpthread.so.0
#18 0x00007f257179eb0d in clone () from /lib64/libc.so.6 
```

Full-Back-Trace
```
(gdb) bt full 
#0  0x00007f2571e9f4fb in raise () from /lib64/libpthread.so.0
No symbol table info available.
#1  0x00007f25737ab337 in crash_handler (signo=6, info=0x7f254e2c6970, ctx=0x7f254e2c6840)
    at /usr/src/debug/nfs-ganesha-4.0.2/MainNFSD/nfs_init.c:256
No locals.
#2  <signal handler called>
No symbol table info available.
#3  0x00007f25716d6387 in raise () from /lib64/libc.so.6
No symbol table info available.
#4  0x00007f25716d7a78 in abort () from /lib64/libc.so.6
No symbol table info available.
#5  0x00007f2573814227 in _dec_session_ref (session=0x7f254a412e00, func=0x7f2573922c70 <__func__.22740> "nfs4_op_destroy_session",
    line=97) at /usr/src/debug/nfs-ganesha-4.0.2/SAL/nfs41_session_id.c:263
        rc = 16
        slot = 0x7f2533535000
        i = 0
        refcnt = 0
        __func__ = "_dec_session_ref"
#6  0x00007f257386714b in nfs4_op_destroy_session (op=0x7f2556c380a0, data=0x7f255302c800, resp=0x7f2556c38000)
    at /usr/src/debug/nfs-ganesha-4.0.2/Protocols/NFS/nfs4_op_destroy_session.c:97
        arg_DESTROY_SESSION4 = 0x7f2556c380a8
        res_DESTROY_SESSION4 = 0x7f2556c38008
        session = 0x7f254a412e00
        __func__ = "nfs4_op_destroy_session"
#7  0x00007f257385fa43 in process_one_op (data=0x7f255302c800, status=0x7f254e2c787c)
    at /usr/src/debug/nfs-ganesha-4.0.2/Protocols/NFS/nfs4_Compound.c:924
        bad_op_state_reason = 0x7f2573920fb3 ""
        perm_flags = 0
        alt_component = COMPONENT_NFS_V4
        thisarg = 0x7f2556c380a0
        thisres = 0x7f2556c38000
        result = 1311537376
        res_compound4 = 0x7f24fa7d4ac0
        __func__ = "process_one_op"
#8  0x00007f2573860acb in nfs4_Compound (arg=0x7f219c59d880, req=0x7f219c59d000, res=0x7f254a591100)
    at /usr/src/debug/nfs-ganesha-4.0.2/Protocols/NFS/nfs4_Compound.c:1339
        status = NFS4_OK
---Type <return> to continue, or q <return> to quit---
        data = 0x7f255302c800
        compound4_minor = 2
        argarray_len = 1
        argarray = 0x7f2556c380a0
        drop = false
        reqdata = 0x7f219c59d000
        res_compound4 = 0x7f24fa7d4ac0
        result = NFS_REQ_OK
        __func__ = "nfs4_Compound"
#9  0x00007f25737a5f80 in nfs_rpc_process_request (reqdata=0x7f219c59d000, retry=false)
    at /usr/src/debug/nfs-ganesha-4.0.2/MainNFSD/nfs_worker_thread.c:2055
        client_ip = 0x7f2559b990cc "::ffff:10.51.19.28"
        progname = 0x7f25738fc94b "NFS"
        reqdesc = 0x7f257396e670 <nfs4_func_desc+48>
        arg_nfs = 0x7f219c59d880
        xprt = 0x7f2558813000
        xdrs = 0x7f24e63bbe40
        dpq_status = DUPREQ_SUCCESS
        auth_rc = AUTH_OK
        port = 712
        rc = 0
        exportid = -1
        no_dispatch = false
        drop_req = false
        __func__ = "nfs_rpc_process_request"
        __PRETTY_FUNCTION__ = "nfs_rpc_process_request"
#10 0x00007f25737a65f9 in nfs_rpc_valid_NFS (req=0x7f219c59d000) at /usr/src/debug/nfs-ganesha-4.0.2/MainNFSD/nfs_worker_thread.c:2293
        reqdata = 0x7f219c59d000
        lo_vers = 32549
        hi_vers = 1457145480
        __func__ = "nfs_rpc_valid_NFS"
#11 0x00007f2573b7ead6 in svc_vc_decode (req=0x7f219c59d000) at /usr/src/debug/nfs-ganesha-4.0.2/libntirpc/src/svc_vc.c:1126
        xdrs = 0x7f24e63bbe40
        xprt = 0x7f2558813000
        __func__ = "svc_vc_decode"
#12 0x00007f2573b79c59 in svc_request (xprt=0x7f2558813000, xdrs=0x7f24e63bbe40)
    at /usr/src/debug/nfs-ganesha-4.0.2/libntirpc/src/svc_rqst.c:1229
---Type <return> to continue, or q <return> to quit---
        stat = 32549
        req = 0x7f219c59d000
        rpc_dplx_rec = 0x7f2558813000
#13 0x00007f2573b7e9db in svc_vc_recv (xprt=0x7f2558813000) at /usr/src/debug/nfs-ganesha-4.0.2/libntirpc/src/svc_vc.c:1099
        rec = 0x7f2558813000
        xd = 0x7f2558813000
        have = 0x0
        uv = 0x7f255e038b00
        xioq = 0x7f24e63bbe40
        rlen = 104
        flags = 2
        code = 32549
        time_diff = 2200758564992
        __func__ = "svc_vc_recv"
        __PRETTY_FUNCTION__ = "svc_vc_recv"
        st = {type = SVC_STATS_RECV, ts = {tv_sec = 104142, tv_nsec = 25395899}}
#14 0x00007f2573b79bbd in svc_rqst_xprt_task_recv (wpe=0x7f25588132f0) at /usr/src/debug/nfs-ganesha-4.0.2/libntirpc/src/svc_rqst.c:1209
        st = {type = SVC_STATS_DISPATCH, ts = {tv_sec = 104142, tv_nsec = 25395899}}
        ioq = 0x7f2558813280
        rec = 0x7f2558813000
        __PRETTY_FUNCTION__ = "svc_rqst_xprt_task_recv"
        __func__ = "svc_rqst_xprt_task_recv"
#15 0x00007f2573b7a840 in svc_rqst_epoll_loop (wpe=0x7f256e91df18) at /usr/src/debug/nfs-ganesha-4.0.2/libntirpc/src/svc_rqst.c:1608
        ioq = 0x7f2558813280
        sr_rec = 0x7f256e91df18
        cc = 0x1888b4b5
        n = 0x0
        ts = {tv_sec = 104135, tv_nsec = 511455633}
        timeout_ms = 29000
        expire_ms = 104135512
        n_events = 1
        finished = false
        __func__ = "svc_rqst_epoll_loop"
#16 0x00007f2573b87cda in work_pool_thread (arg=0x7f255ec32da0) at /usr/src/debug/nfs-ganesha-4.0.2/libntirpc/src/work_pool.c:190
        wpt = 0x7f255ec32da0
        pool = 0x7f256e835800
        have = 0x7f256e91df18
---Type <return> to continue, or q <return> to quit---
        ts = {tv_sec = 1668105177, tv_nsec = 523446554}
        rc = 0
        spawn = false
        __func__ = "work_pool_thread"
#17 0x00007f2571e97ea5 in start_thread () from /lib64/libpthread.so.0
No symbol table info available.
#18 0x00007f257179eb0d in clone () from /lib64/libc.so.6
No symbol table info available

```

Findings: 
We destroy the session, if its ref count becomes 0.
Here we are destroying the mutex on line 263, and it gave segmentation fault.
On gdb we found that some slots were already destroyed in the session and
other were valid.

```
239 int32_t _dec_session_ref(nfs41_session_t *session, const char *func, int line)
240 {
241         int i;
242         int32_t refcnt = atomic_dec_int32_t(&session->refcount);
243 #ifdef USE_LTTNG
244         tracepoint(nfs4, session_unref, func, line, session, refcnt);
245 #endif
246
247         if (refcnt == 0) {
248
249                 /* Unlink the session from the client's list of
250                    sessions */
251                 PTHREAD_MUTEX_lock(&session->clientid_record->cid_mutex);
252                 glist_del(&session->session_link);
253                 PTHREAD_MUTEX_unlock(&session->clientid_record->cid_mutex);
254
255                 /* Decrement our reference to the clientid record */
256                 dec_client_id_ref(session->clientid_record);
257                 /* Destroy this session's mutexes and condition variable */
258
259                 for (i = 0; i < session->nb_slots; i++) {
260                         nfs41_session_slot_t *slot;
261
262                         slot = &session->fc_slots[i];
263                         PTHREAD_MUTEX_destroy(&slot->lock);
264                         release_slot(slot);
265                 }
265 } 
266  

```
valid and freed slots :
```
(gdb) p *(session->fc_slots + 53 )
$84 = {sequence = 3, lock = {_data = {_lock = 0, __count = 0, __owner = 0, __nusers = 0, __kind = 0,
      __spins = 0, __elision = 0, _list = {_prev = 0x0, __next = 0x0}}, __size = '\000' <repeats 39 times>,
    __align = 0}, cached_result = 0x7f24f5c89dc0}
(gdb) p *(session->fc_slots + 54 )
$85 = {sequence = 0, lock = {_data = {_lock = 0, __count = 0, __owner = 0, __nusers = 0, __kind = 0,
      __spins = 0, __elision = 0, _list = {_prev = 0x0, __next = 0x0}}, __size = '\000' <repeats 39 times>,
    __align = 0}, cached_result = 0x0}
```

Original Thread: [click](https://lists.nfs-ganesha.org/archives/list/devel@lists.nfs-ganesha.org/thread/FUFBSOCWOLCELU3ZGUKIQ2NSUTY7BH7N/)
cc: @ffilz @dang @Gaurav-Gangalwar @pradeepthomas

**Comment by ffilz** [comment]
Do you have a solid recreate for this? I'd like to run with some debug enabled which should help suss out the refcount issue that is presumably at fault.

**Comment by ffilz** [comment]
We have had some fixes related to session refcount. Please try with Ganesha V4.3

**Comment by ffilz** [comment]
No response in over 30 days. Closing.
