### ISSUE TITLE
ganesha_stats not working on RHEL7.9

### ISSUE THREAD

**Issue by yogendra-t** [nfs-ganesha/nfs-ganesha#891]
[root@rhel79y2 RHEL7]# ganesha_stats
Traceback (most recent call last):
  File "/usr/bin/ganesha_stats", line 148, in <module>
    result = exp_interface.global_stats()
  File "/usr/lib/python2.7/site-packages/Ganesha/glib_dbus_stats.py", line 125, in global_stats
    return GlobalStats(stats_op())
  File "/usr/lib/python2.7/site-packages/Ganesha/glib_dbus_stats.py", line 817, in __init__
    super().__init__(stats)
TypeError: super() takes at least 1 argument (0 given)

**Comment by ffilz** [comment]
Ganesha's python scripts require python3

**Comment by ffilz** [comment]
Closing old issues that are not planned for any resolution.

Please re-open with new information if this issue is still of concern.
