### ISSUE TITLE
Some nfs ganesha utilities are not working with python 3

### ISSUE THREAD

**Issue by pranesh005** [nfs-ganesha/nfs-ganesha#964]
We tried installing both nfs-ganesha 4 and 5, some of the utilities like ganesha_stats, grace_period and ganesha_mgr is working fine, whereas utils like ganesha_conf , ganeshactl and all other GUI utilities requires some Python 2 to 3 conversion and PyQt5 changes.

Also utilities like get_clientids and fake_recall is not working. 
```
[root@ganesha-open rpms]# get_clientids
introspection data
<!DOCTYPE node PUBLIC "-//freedesktop//DTD D-BUS Object Introspection 1.0//EN"
"http://www.freedesktop.org/standards/dbus/1.0/introspect.dtd">
<node>
</node>

client ids:
Traceback (most recent call last):
  File "/bin/get_clientids", line 41, in <module>
    print(get_client_ids())
  File "/usr/lib64/python3.6/site-packages/dbus/proxies.py", line 145, in __call__
    **keywords)
  File "/usr/lib64/python3.6/site-packages/dbus/connection.py", line 651, in call_blocking
    message, timeout)
dbus.exceptions.DBusException: org.freedesktop.DBus.Error.UnknownMethod: Method "get_client_ids" with signature "" on interface "org.ganesha.nfsd.cbsim" doesn't exist
``` 

Is there any plans of fixing these issues in upcoming releases ?

**Comment by ffilz** [comment]
We would welcome contributions to make these scripts work. Unfortunately at the moment, our resources are limited for resolving these issues.

**Comment by rohitrs1983** [comment]
@pranesh005 the above issue regarding "get_clientids" is because ganesha is not built with USE_CB_SIMULATOR
the DBUS org.ganesha.nfsd.cbsim methods list is built under USE_CB_SIMULATOR flag.
please enable USE_CB_SIMULATOR and rebuild ganesha. it should work fine.

**Comment by ffilz** [comment]
Closing really old issues with no response.
